import { describe, expect, test } from 'bun:test'

const source = (path: string) => Bun.file(path).text()

describe('Catálogo V3: estructura principal', () => {
  test('las rutas cargan Catálogo y Productos como módulos lazy separados', async () => {
    const app = await source('src/features/solog/admin/admin.v2.app.tsx')
    expect(app).toMatch(/import\(\s*["']\.\/catalogo\/admin\.catalogo\.page\.v3["']\s*\)/)
    expect(app).toMatch(/default:\s*m\.AdminCatalogV3/)
    expect(app).toMatch(/import\(\s*["']\.\/productos\/admin\.productos\.v1["']\s*\)/)
    expect(app).toMatch(/default:\s*m\.AdminProductsV1/)
  })

  test('Catálogo conserva Propuestas y retira la pestaña y lectura Productos', async () => {
    const ui = await source('src/features/solog/admin/catalogo/admin.catalogo.page.v3.tsx')
    expect(ui).toMatch(/useCatalogQuery\(\s*["']status["']\s*,\s*\{\s*\}\s*\)/)
    expect(ui).toContain('<ProposalsSurface />')
    expect(ui).not.toMatch(/useCatalogQuery\(\s*["']products["']/)
    expect(ui).not.toContain('ProductsSurface')
    expect(ui).not.toContain('Superficies de Catálogo')
    expect(ui).not.toContain('PageControls')
    expect(ui).not.toContain('useManagement')
    expect(ui).not.toContain('limit: 50')
    expect(ui).not.toContain('offset')
  })

  test('consume los cuatro estados y conserva la clasificación y acciones de Propuestas V3', async () => {
    const ui = await source('src/features/solog/admin/catalogo/admin.catalogo.page.v3.tsx')
    const setup = await source('src/features/solog/admin/productos/admin.product-setup.dialog.tsx')
    for (const status of ['pendiente', 'aprobado', 'ignorado', 'incorporado']) expect(ui).toMatch(new RegExp(`\\{\\s*id:\\s*["']${status}["']`))
    for (const urgent of ['agregar_producto', 'precio', 'reincorporar_producto']) expect(ui).toMatch(new RegExp(`["']${urgent}["']`))
    for (const emerging of ['eliminar_producto', 'excluir_producto', 'nombre', 'codigo']) expect(ui).toMatch(new RegExp(`["']${emerging}["']`))
    expect(ui).toMatch(/store\s*\.\s*mutation\(\s*["']proposal_action["']/)
    expect(ui).toMatch(/run\(\s*["']withdraw["']\s*\)/)
    expect(ui).toContain('Candidato automático')
    expect(ui).toContain('proposal.stale')
    expect(ui).toContain('proposal.block_reason')
    expect(ui).not.toContain('admin.package-price.v2')
    expect(setup).toMatch(/store\s*\.\s*mutation\(\s*["']prepare_product["']/)
    expect(setup).toContain('useMasterData()')
    expect(setup).not.toMatch(/useCatalogQuery\(\s*["']reference["']/)
    expect(ui).toMatch(/store\s*\.\s*mutation\(\s*["']prepare_price["']/)
    expect(ui).toMatch(/useCatalogQuery\(\s*["']price_options["']/)
    expect(ui).toMatch(/useCatalogQuery\(\s*["']publication_preview["']\s*,\s*\{\s*\}\s*\)/)
    expect(ui).toContain('store.publish()')
  })

  test('expone estados UI, reintentos y controles accesibles de staging y publicación', async () => {
    const ui = await source('src/features/solog/admin/catalogo/admin.catalogo.page.v3.tsx')
    for (const state of ['QueryState', 'role="alert"', 'role="status"', 'Reintentar misma operación', 'No hay propuestas', 'Existe staging preparado', 'No publicable:', 'Confirmar publicación', 'Recuperar publicación']) expect(ui).toContain(state)
    expect(ui).toContain('aria-label="Estado de propuestas"')
    expect(ui).toMatch(/disabled=\{\s*!admin\s*\|\|\s*!!receipt\.pending\s*\|\|\s*\(\s*!receipt\.operationId\s*&&\s*!preview\?\.ok\s*\)\s*\}/s)
  })

  test('Productos opera sobre Master Data completo y conserva las mutaciones Catálogo V3', async () => {
    const ui = await source('src/features/solog/admin/productos/admin.productos.v1.tsx')
    expect(ui).toContain('useMasterData()')
    expect(ui).toContain('masterData.snapshot.totals.products')
    expect(ui).toContain('masterData.snapshot.setup_required')
    expect(ui).toContain('derived.categoryById')
    expect(ui).toContain('derived.groupById')
    expect(ui).toMatch(/store\s*\.\s*mutation\(\s*["']propose_product_state["']/)
    expect(ui).toMatch(/action\s*===\s*["']exclude["'][\s\S]*?["']Proponer exclusión["'][\s\S]*?:[\s\S]*?["']Proponer reincorporación["']/)
    expect(ui).toContain('No modifica el estado del producto ahora.')
    expect(ui).not.toMatch(/useCatalogQuery\(\s*["']products["']/)
    expect(ui).not.toContain('group_products')
    expect(ui).not.toContain('catalog_change_action')
  })
})
test('la tabla de propuestas compone identidad y Cambio sin lecturas adicionales', async () => {
  const ui = await source('src/features/solog/admin/catalogo/admin.catalogo.page.v3.tsx')
  expect(ui).toMatch(/<th\s+scope=["']col["']>Producto<\/th>[\s\S]*?<th\s+scope=["']col["']>Cambio<\/th>[\s\S]*?<th\s+scope=["']col["']>Origen<\/th>[\s\S]*?<th\s+scope=["']col["']>Acción<\/th>/)
  expect(ui).not.toMatch(/<th\s+scope=["']col["']>C\. interno<\/th>/)
  expect(ui).toContain('admin-catalog__product-code')
  expect(ui).toContain('admin-catalog__product-name')
  expect(ui).toContain('catalogProposalChange(proposal)')
  expect(ui).toMatch(/\?\s*["']Automático["']/)
  expect(ui).toMatch(/:\s*proposal\.sedes[\s\S]*?\|\|\s*["']Propuesto["']/)
})


test('Cambio conserva la flecha visual y expone una relación accesible anterior a nuevo', async () => {
  const ui = await source('src/features/solog/admin/catalogo/admin.catalogo.page.v3.tsx')
  expect(ui).toContain('function accessibleChangeValue')
  expect(ui).toContain('aria-hidden="true"')
  expect(ui).toContain('admin-catalog__change-sr')
  expect(ui).toContain('cambia a nuevo')
  expect(ui).toMatch(/change\.kind\s*===\s*["']price["']/)
  expect(ui).toMatch(/change\.kind\s*===\s*["']text["']/)
})
