// Shell + Dispositivos UI. Every non-local request is intercepted; no production traffic.
import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import { createServer } from 'vite'
import { bootstrapFixture, responseFixture } from './fixtures/admin-v2.mjs'
import { managementFixture } from './fixtures/admin-management.mjs'

const { chromium } = await import(pathToFileURL(process.env.SOLOG_PLAYWRIGHT_MODULE).href)
const server = await createServer({ server: { host: '127.0.0.1', port: 5222, strictPort: true }, define: {
  'import.meta.env.VITE_SUPABASE_URL': JSON.stringify('https://solog-admin-v2.test'),
  'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify('test-only'),
} })
await server.listen()
const browser = await chromium.launch({ headless: true, executablePath: process.env.SOLOG_TEST_BROWSER })
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } })
const now = new Date().toISOString()
const sites = ['Casuarinas', 'Unidad', 'Divino', 'Huaca', 'Cutervo'].map((nombre, i) => ({ id: 'site-' + i, nombre, operational_revision: 10, devices_revision: 2, incidents_revision: 4 }))
const user = { id: 'admin-test', email: 'admin@example.test', role: 'authenticated', app_metadata: {}, user_metadata: {}, aud: 'authenticated', created_at: now }
const exp = Math.floor(Date.now() / 1000) + 3600
const jwt = [{ alg: 'HS256', typ: 'JWT' }, { sub: user.id, aud: 'authenticated', role: 'authenticated', exp }].map(p => Buffer.from(JSON.stringify(p)).toString('base64url')).join('.') + '.test'
await context.addInitScript(({ user, jwt, exp }) => localStorage.setItem('sb-solog-admin-v2-auth-token', JSON.stringify({ access_token: jwt, refresh_token: 'test', expires_at: exp, expires_in: 3600, token_type: 'bearer', user })), { user, jwt, exp })
const device = (siteIndex, state, suffix) => ({
  id: '84f12648-0000-4000-8000-0000000016' + suffix, site_id: sites[siteIndex].id, site: sites[siteIndex].nombre,
  estado: state, solicitado_por: 'cashier-' + siteIndex, solicitante: 'Cajero ' + sites[siteIndex].nombre,
  solicitado_at: now, autorizado_at: state === 'autorizado' ? now : null, ultimo_acceso_at: now, revision: 2,
})
let devices = [device(4, 'autorizado', '3f'), device(3, 'autorizado', '4f'), device(3, 'pendiente', '5f'), device(2, 'pendiente', '6f')]
const calls = [], errors = []
let failList = false, heldMutation, holdControlRead = false, releaseControlRead
await context.route('**/*', async route => {
  const url = new URL(route.request().url())
  if (url.hostname === '127.0.0.1') return route.continue()
  if (url.hostname !== 'solog-admin-v2.test') { errors.push('External: ' + url.hostname); return route.abort() }
  const fulfill = (data, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(data) })
  if (url.pathname === '/auth/v1/user') return fulfill(user)
  if (url.pathname === '/auth/v1/logout') return fulfill({})
  const rpc = url.pathname.split('/').at(-1), body = route.request().postDataJSON()
  assert.ok(['rpc_solog_admin_bootstrap_v2', 'rpc_solog_operational_v2', 'rpc_solog_admin_devices_v2', 'rpc_solog_admin_master_read_v2', 'rpc_solog_admin_incidents_v2'].includes(rpc), rpc)
  const action = rpc === 'rpc_solog_admin_bootstrap_v2' ? 'bootstrap' : body.p_action, p = body.p_payload
  calls.push({ rpc, action, payload: p })
  if (action === 'bootstrap') return fulfill({ ...bootstrapFixture(), identity: { ...bootstrapFixture().identity, nombre: 'Gerencia' }, allowed_sites: sites })
  if (action === 'dashboard_cards') return fulfill({ ...responseFixture(action), sites: sites.map(site => ({ ...responseFixture(action).sites[0], site_id: site.id, site: site.nombre,
    period_coverage: site.id === 'site-1' ? { counted: 0, total: 0, percent: 0, complete: false } : site.id === 'site-2' ? { counted: 483, total: 483, percent: 100, complete: true } : { counted: 7, total: 483, percent: 1.4, complete: false },
    daily_coverage: { counted_today: 0, total: 483, percent: 0 },
    pending_recount: site.id === 'site-3' ? 2 : 0,
    snapshot: site.id === 'site-0' ? null : responseFixture(action).sites[0].snapshot,
  })) })
  if (action === 'shift_grid' && p.site_id === 'site-1') return fulfill({ ...responseFixture(action, p), data: { shifts: [], totals: [] } })
  if (action === 'shift_grid') {
    const grid = responseFixture(action, p)
    const dates = Array.from({ length: 15 }, (_, i) => `2026-09-${String(i + 1).padStart(2, '0')}`)
    return fulfill({ ...grid, data: {
      shifts: dates.flatMap(date => grid.data.shifts.map(shift => ({ ...shift, date }))),
      totals: dates.map(date => ({ ...grid.data.totals[0], date })),
    } })
  }
  if (action === 'control_groups') {
    const data = responseFixture(action, p)
    const ranges = { today: ['2026-09-03', '2026-09-03'], last_week: ['2026-08-28', '2026-09-03'], current_biweekly: ['2026-09-01', '2026-09-15'], previous_biweekly: ['2026-08-16', '2026-08-31'] }
    if (ranges[p.period]) [data.period.from, data.period.to] = ranges[p.period]
    if (holdControlRead) await new Promise(resolve => { releaseControlRead = resolve })
    if (p.site_id === 'site-1') return fulfill({ ...data, items: [] })
    return fulfill(data)
  }
  if (rpc === 'rpc_solog_operational_v2') return fulfill(responseFixture(action, p))
  if (action === 'list') {
    assert.deepEqual(p, {})
    if (failList) { failList = false; return fulfill({ message: 'Fallo de lectura simulado', code: '500' }, 500) }
    return fulfill({ contract_version: 2, generated_at: now, devices })
  }
  if (rpc === 'rpc_solog_admin_devices_v2') {
    assert.deepEqual(Object.keys(p).sort(), ['device_id', 'expected_revision', 'operation_id'])
    assert.equal(action, 'authorize')
    const target = devices.find(d => d.id === p.device_id)
    assert.equal(target.site, 'Divino')
    assert.equal(p.expected_revision, target.revision)
    assert.match(p.operation_id, /^[0-9a-f-]{36}$/)
    await new Promise(resolve => { heldMutation = resolve })
    devices = devices.map(d => d.id === p.device_id ? { ...d, estado: 'autorizado', autorizado_at: now, revision: 3 } : d)
    const authorized = devices.find(d => d.id === p.device_id)
    return fulfill({ contract_version: 2, generated_at: now, replay: false, action, revisions: { devices: 3 }, site_id: target.site_id, authorized_device: authorized, pending_devices: [] })
  }
  return fulfill(managementFixture(action, p))
})
const page = await context.newPage()
page.setDefaultTimeout(12000)
page.on('pageerror', e => errors.push(e.message))
const nav = name => page.getByRole('navigation', { name: 'Módulos administrativos' }).getByRole('button', { name, exact: true }).click()
const headerSites = () => page.getByRole('group', { name: 'Sede administrativa' })
const count = action => calls.filter(call => call.action === action).length
const screenshot = async suffix => {
  if (process.env.SOLOG_SHELL_SCREENSHOT) await page.screenshot({ path: process.env.SOLOG_SHELL_SCREENSHOT.replace('.png', '-' + suffix + '.png'), fullPage: true, animations: 'disabled' })
}
try {
  const controlOnly = process.env.SOLOG_CONTROL_UI_ONLY === '1'
  await page.goto('http://127.0.0.1:5222/admin' + (controlOnly ? '/control' : ''))
  if (!controlOnly) {
  await page.getByRole('heading', { name: 'Cutervo', exact: true }).waitFor()
  assert.equal(await headerSites().count(), 0)
  const dashboardLogo = page.locator('.admin-header').getByRole('img', { name: 'Puerto Rico', exact: true })
  assert.equal(await dashboardLogo.getAttribute('src'), '/logo-pr-light.png')
  assert.equal(await dashboardLogo.evaluate(image => !!image.closest('button, a')), false)
  const dashboard = page.getByRole('region', { name: 'Resumen por sede' })
  assert.deepEqual(await dashboard.getByRole('heading').allTextContents(), ['Cutervo', 'Huaca', 'Divino', 'Unidad', 'Casua'])
  const boxes = await dashboard.getByRole('article').evaluateAll(cards => cards.map(card => { const r = card.getBoundingClientRect(); return { x: r.x, y: r.y, width: r.width, bottom: r.bottom } }))
  assert.ok(boxes.every((box, i) => box.x === boxes[0].x && box.width === boxes[0].width && (!i || box.y > boxes[i - 1].bottom)))
  assert.equal(await dashboard.locator('[aria-expanded="true"]').count(), 0)
  assert.equal(count('shift_grid'), 0)
  assert.equal(count('dashboard_cards'), 1)
  assert.deepEqual(calls.find(call => call.action === 'dashboard_cards').payload, {})
  const cutervo = page.getByRole('article', { name: 'Sede Cutervo', exact: true })
  assert.equal(await cutervo.getByRole('progressbar').getAttribute('value'), '1.4')
  assert.ok((await cutervo.boundingBox()).height < 180, 'Card compacta frente a los 196px anteriores')
  assert.equal(await cutervo.getByText('0 pendientes', { exact: true }).count(), 1)
  assert.equal(await cutervo.locator('.lucide-triangle-alert').count(), 0)
  const huaca = page.getByRole('article', { name: 'Sede Huaca', exact: true })
  assert.equal(await huaca.getByText('2 pendientes', { exact: true }).count(), 1)
  assert.equal(await huaca.locator('.lucide-triangle-alert').count(), 1)
  const divino = page.getByRole('article', { name: 'Sede Divino', exact: true })
  assert.equal(await divino.getByRole('progressbar', { name: 'Cobertura diaria' }).getAttribute('value'), '0')
  assert.equal(await divino.getByText('Quincena completada', { exact: true }).count(), 1)
  assert.equal(await divino.locator('.admin-dashboard__complete .lucide-check').count(), 1)
  assert.match(await cutervo.innerText(), /7 \/ 483 · 1.4%/)
  assert.match(await cutervo.locator('time').innerText(), /3 (?:sep|set).*5:30 pm/)
  const unidad = page.getByRole('article', { name: 'Sede Unidad', exact: true })
  assert.equal(await unidad.getByText('Sin cobertura registrada').count(), 1)
  assert.equal(await unidad.getByRole('progressbar').count(), 0)
  assert.equal(await dashboard.getByText(/0 \/ 0/).count(), 0)
  assert.equal(await page.getByRole('article', { name: 'Sede Casua' }).getByText('Sin snapshot confirmado').count(), 1)
  assert.equal(await page.getByText(/Actualizado/).count(), 0)
  await screenshot('dashboard-closed')
  const dashboardThemes = []
  assert.deepEqual(await page.locator('.admin-main-tabs__label').allTextContents(), ['OPERACIÓN', 'GESTIÓN', 'APARIENCIA'])
  assert.equal(await page.getByRole('button', { name: /Actualizar Admin/ }).count(), 0)
  const initialCalls = calls.length
  for (const [name, palette] of [['Prisma', 'violet'], ['Natura', 'green'], ['Órbita', 'blue']]) {
    await page.getByRole('button', { name, exact: true }).click()
    assert.equal(await page.getByRole('button', { name, exact: true }).getAttribute('aria-pressed'), 'true')
    assert.equal(await page.evaluate(() => document.documentElement.dataset.palette), palette)
    assert.equal(await page.evaluate(() => localStorage.getItem('solog.palette.v1')), palette)
    dashboardThemes.push(await page.evaluate(() => {
      const style = selector => getComputedStyle(document.querySelector(selector))
      return { header: style('.admin-header').backgroundImage, card: style('.admin-dashboard__card').backgroundColor, panel: style('.admin-v2-workspace').backgroundColor, warning: style('.admin-dashboard__warning').color, accent: style('.admin-dashboard').getPropertyValue('--color-primary'), chip: style('.admin-dashboard__complete').backgroundColor, chipColor: style('.admin-dashboard__complete').color }
    }))
    await screenshot('dashboard-' + palette)
  }
  assert.equal(calls.length, initialCalls)
  for (const key of ['header', 'card', 'panel', 'warning']) assert.equal(new Set(dashboardThemes.map(theme => theme[key])).size, 1)
  assert.equal(new Set(dashboardThemes.map(theme => theme.accent)).size, 3)
  assert.equal(new Set(dashboardThemes.map(theme => theme.chip)).size, 3)
  assert.equal(new Set(dashboardThemes.map(theme => theme.chipColor)).size, 3)
  await page.getByRole('button', { name: 'Ver turnos de Cutervo' }).click()
  await cutervo.getByRole('columnheader', { name: 'Jue 03', exact: true }).waitFor()
  assert.deepEqual((await cutervo.getByRole('columnheader').allTextContents()).slice(1, 8), ['Mar 01', 'Mié 02', 'Jue 03', 'Vie 04', 'Sáb 05', 'Dom 06', 'Lun 07'])
  assert.equal(await cutervo.getByRole('columnheader').count(), 16)
  assert.equal(await cutervo.locator('.admin-v2-table').evaluate(node => node.scrollWidth > node.clientWidth && getComputedStyle(node).overflowX === 'auto'), true)
  assert.equal(await dashboard.locator('[aria-expanded="true"]').count(), 1)
  assert.equal(await dashboard.getByText(/Actualizado|07:30|15:30|00:00|2026-/).count(), 0)
  await screenshot('dashboard-cutervo')
  const tableScroll = cutervo.locator('.admin-v2-table')
  const stickyBefore = await tableScroll.locator('th:first-child').evaluateAll(cells => cells.map(cell => cell.getBoundingClientRect().x))
  await tableScroll.evaluate(node => { node.scrollLeft = 400 })
  await page.waitForFunction(() => document.querySelector('.admin-dashboard__detail > .admin-v2-table').scrollLeft > 0)
  const stickyAfter = await tableScroll.locator('th:first-child').evaluateAll(cells => cells.map(cell => cell.getBoundingClientRect().x))
  assert.deepEqual(stickyAfter, stickyBefore)
  assert.equal(await tableScroll.locator('thead th').first().evaluate(node => getComputedStyle(node).zIndex), '3')
  assert.equal(await tableScroll.locator('tbody th').first().evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(255, 255, 255)')
  assert.equal(await tableScroll.locator('thead th').nth(1).evaluate(node => getComputedStyle(node).position), 'sticky')
  // Exercise the sticky header with a constrained viewport, without changing application CSS.
  await tableScroll.evaluate(node => { node.style.maxHeight = '140px'; node.scrollTop = 50 })
  await page.waitForFunction(() => document.querySelector('.admin-dashboard__detail > .admin-v2-table').scrollTop > 0)
  assert.ok(Math.abs((await tableScroll.locator('thead th').nth(1).boundingBox()).y - (await tableScroll.boundingBox()).y) < 2)
  await screenshot('dashboard-sticky')
  await tableScroll.evaluate(node => { node.style.removeProperty('max-height'); node.scrollTop = 0; node.scrollLeft = 0 })
  const periodSelect = cutervo.getByRole('combobox', { name: 'Quincena de turnos' })
  assert.equal(await periodSelect.evaluate(node => getComputedStyle(node).boxShadow), 'none')
  await periodSelect.focus()
  assert.equal(await periodSelect.evaluate(node => getComputedStyle(node).outlineStyle), 'solid')
  assert.equal(await periodSelect.evaluate(node => getComputedStyle(node).outlineWidth), '2px')
  await screenshot('dashboard-period-focus')
  await page.getByRole('button', { name: 'Ver turnos de Huaca' }).click()
  await page.getByRole('article', { name: 'Sede Huaca' }).getByRole('columnheader', { name: 'Jue 03', exact: true }).waitFor()
  assert.equal(await cutervo.getByRole('table').count(), 0)
  assert.equal(await dashboard.locator('[aria-expanded="true"]').count(), 1)
  await screenshot('dashboard-huaca')
  await page.getByRole('button', { name: 'Ocultar turnos de Huaca' }).click()
  assert.equal(await dashboard.locator('[aria-expanded="true"]').count(), 0)
  assert.equal(await dashboard.getByRole('table').count(), 0)
  await page.getByRole('button', { name: 'Ver turnos de Cutervo' }).click()
  await cutervo.getByRole('table').waitFor()
  assert.equal(count('shift_grid'), 2, 'Reabrir usa caché por sede, no refetch')
  await page.getByRole('button', { name: 'Ver turnos de Unidad' }).click()
  await unidad.getByText('Sin datos de turnos').waitFor()
  assert.equal(await unidad.getByRole('table').count(), 0)
  await page.getByRole('button', { name: 'Ocultar turnos de Unidad' }).click()
  await page.setViewportSize({ width: 850, height: 1000 })
  await page.getByRole('button', { name: 'Alternar navegación' }).click()
  await page.waitForFunction(() => document.querySelector('.admin-sidebar').getBoundingClientRect().width <= 72)
  assert.equal(await dashboard.getByRole('article').count(), 5)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await page.getByRole('button', { name: 'Ver turnos de Cutervo' }).click()
  await cutervo.getByRole('table').waitFor()
  assert.equal(await cutervo.locator('.admin-v2-table').evaluate(node => node.scrollWidth > node.clientWidth), true)
  await screenshot('dashboard-tablet')
  await page.getByRole('button', { name: 'Ocultar turnos de Cutervo' }).click()
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole('button', { name: 'Alternar navegación' }).click()
  await page.waitForFunction(() => document.querySelector('.admin-sidebar').getBoundingClientRect().width > 200)
  }
  await nav('Control')
  await page.getByText('Grupo 99', { exact: true }).waitFor()
  assert.deepEqual(await headerSites().getByRole('button').allTextContents(), ['Cutervo', 'Huaca', 'Divino', 'Unidad', 'Casua'])
  assert.equal(await headerSites().getByRole('button', { name: 'Cutervo', exact: true }).getAttribute('aria-pressed'), 'true')
  const dimensions = await headerSites().getByRole('button').evaluateAll(buttons => buttons.map(button => [button.getBoundingClientRect().width, button.getBoundingClientRect().height]))
  assert.ok(dimensions.every(size => JSON.stringify(size) === JSON.stringify(dimensions[0])))
  await headerSites().getByRole('button', { name: 'Huaca', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.admin-site-context button[aria-pressed="true"]').textContent === 'Huaca')
  await page.getByText('Grupo 99', { exact: true }).waitFor()
  assert.equal(calls.filter(c => c.action === 'control_groups').at(-1).payload.site_id, 'site-3')
  assert.equal(await page.getByLabel('Sede', { exact: true }).count(), 0)
  const control = page.locator('.admin-control')
  assert.equal(await control.getByText(/Consulta aplicada|Actualizado/).count(), 0)
  assert.equal(await control.locator('.admin-control__chip').count(), 5)
  assert.deepEqual(await control.locator('.admin-control__badge').allTextContents().then(values => values.slice(0, 4)), ['Coincide', 'Por recontar', 'Confirmada', 'Inconsistente'])
  assert.equal(await control.locator('.admin-control__difference--positive').first().innerText(), '+2')
  assert.equal(await control.locator('.admin-control__difference--negative').first().innerText(), '-2')
  assert.equal(await control.locator('.admin-control__difference--zero').first().innerText(), '0')
  assert.match(await control.locator('time').first().innerText(), /3 (set|sep).*5:30 pm/)
  const detailButton = control.getByRole('button', { name: 'Ver cronología de Grupo 0', exact: true })
  assert.equal(await detailButton.locator('.lucide-eye').count(), 1)
  assert.equal(await detailButton.innerText(), '')
  const periodTrigger = control.getByRole('combobox', { name: 'Período', exact: true })
  const initialRange = await periodTrigger.innerText()
  assert.match(initialRange, /03 (set|sep)\. — 03 (set|sep)\./)
  const beforeSelection = count('control_groups')
  assert.equal(await control.getByLabel('Estado', { exact: true }).count(), 0)
  assert.equal(await control.getByRole('button', { name: 'Aplicar filtros' }).count(), 0)
  await periodTrigger.click()
  assert.deepEqual(await control.getByRole('listbox').getByRole('option').allTextContents(), ['Hoy', 'Última semana', 'Período actual quincenal', 'Período anterior quincenal', 'Personalizado'])
  await page.keyboard.press('Escape')
  assert.equal(await periodTrigger.getAttribute('aria-expanded'), 'false')
  assert.equal(await periodTrigger.evaluate(node => node === document.activeElement), true)
  holdControlRead = true
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('End')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await control.getByRole('status').waitFor()
  assert.equal(await periodTrigger.innerText(), 'Última semana', 'Uncached selection shows its own label, never stale dates')
  for (let i=0; !releaseControlRead && i<100; i++) await new Promise(resolve=>setTimeout(resolve,20))
  assert.equal(typeof releaseControlRead,'function')
  holdControlRead = false
  releaseControlRead()
  await periodTrigger.filter({ hasText: /28 ago\. — 03 (set|sep)\./ }).waitFor()
  assert.equal(count('control_groups'), beforeSelection + 1)
  for (const [label, expected] of [['Período actual quincenal', /01 (set|sep)\. — 15 (set|sep)\./], ['Período anterior quincenal', /16 ago\. — 31 ago\./], ['Personalizado', /03 (set|sep)\. — 11 (set|sep)\./]]) {
    const before = count('control_groups')
    await periodTrigger.click()
    await control.getByRole('option', { name: label, exact: true }).click()
    if (label === 'Personalizado') {
      assert.equal(await periodTrigger.innerText(),'Personalizado')
      await control.getByLabel('Desde', { exact: true }).fill('2026-09-03')
      assert.equal(count('control_groups'),before)
      await control.getByLabel('Hasta', { exact: true }).fill('2026-09-11')
    }
    await periodTrigger.filter({ hasText: expected }).waitFor()
    assert.equal(count('control_groups'), before + 1)
  }
  await periodTrigger.click()
  await screenshot('control-period-open')
  await page.locator('.admin-header').click()
  assert.equal(await periodTrigger.getAttribute('aria-expanded'), 'false')
  await periodTrigger.focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('Tab')
  assert.equal(await periodTrigger.getAttribute('aria-expanded'), 'false')
  const beforeCached = count('control_groups')
  await periodTrigger.click()
  await control.getByRole('option', { name: 'Hoy', exact: true }).click()
  await periodTrigger.filter({ hasText: initialRange }).waitFor()
  assert.equal(count('control_groups'),beforeCached)
  const beforeChips = count('control_groups')
  const totals = await control.locator('.admin-control__chip').allTextContents()
  for (const [label, badge] of [['Coinciden','Coincide'],['Recontar','Por recontar'],['Confirmadas','Confirmada'],['Inconsistentes','Inconsistente'],['Total',null]]) {
    const chip = control.locator('.admin-control__chip').filter({ hasText: label })
    await chip.click()
    assert.equal(await chip.getAttribute('aria-pressed'), 'true')
    assert.equal(await control.locator('.admin-control__chip[aria-pressed="true"]').count(), 1)
    assert.deepEqual(await control.locator('.admin-control__chip').allTextContents(),totals)
    if(badge)assert.ok((await control.locator('.admin-control__badge').allTextContents()).every(value=>value===badge))
  }
  await control.locator('.admin-control__chip').filter({hasText:'Recontar'}).focus()
  await page.keyboard.press('Space')
  await control.getByLabel('Buscar grupo').fill('Grupo 1')
  assert.deepEqual(await control.locator('tbody tr td:first-child').allTextContents(),['Grupo 1','Grupo 13','Grupo 17'])
  assert.equal(count('control_groups'), beforeChips, 'Chips/search filter immediately with zero RPC')
  await control.getByLabel('Buscar grupo').fill('')
  console.log('PASS Control block 2: automatic periods, pending label, custom validity, cached ranges, keyboard, local-only chips and search')
  const controlThemes = []
  for (const name of ['Órbita', 'Prisma', 'Natura']) {
    await page.getByRole('button', { name, exact: true }).click()
    controlThemes.push(await control.evaluate(node => {
      const style = selector => getComputedStyle(node.querySelector(selector))
      return { table: style('.admin-control__table').backgroundColor, badge: style('.admin-control__badge.admin-control__tone--warning').backgroundColor, button: style('.admin-control__period-trigger').getPropertyValue('--color-primary') }
    }))
    await screenshot('control-huaca-' + name)
  }
  assert.equal(new Set(controlThemes.map(theme => theme.table)).size, 1)
  assert.equal(new Set(controlThemes.map(theme => theme.badge)).size, 1)
  assert.equal(new Set(controlThemes.map(theme => theme.button)).size, 3)
  await control.locator('.admin-control__chip').filter({hasText:'Total'}).click()
  const title=control.getByRole('heading',{name:'Control de diferencias',exact:true})
  await title.scrollIntoViewIfNeeded()
  assert.ok((await title.boundingBox()).y >= (await page.locator('.admin-header').boundingBox()).y + (await page.locator('.admin-header').boundingBox()).height)
  const table = control.locator('.admin-control__table')
  await table.evaluate(node => { node.scrollTop = 150 })
  await page.waitForFunction(() => document.querySelector('.admin-control__table').scrollTop > 0)
  assert.ok(Math.abs((await table.getByRole('columnheader').first().boundingBox()).y - (await table.boundingBox()).y) < 3)
  await screenshot('control-sticky')
  await headerSites().getByRole('button', { name: 'Unidad', exact: true }).click()
  await control.getByText('No hay resultados para los filtros seleccionados.').waitFor()
  assert.equal(calls.filter(call => call.action === 'control_groups').at(-1).payload.site_id, 'site-1')
  assert.equal(await control.getByRole('table').count(), 0)
  assert.equal(await control.getByText(/Página/).count(), 0)
  assert.equal(await control.getByRole('button', { name: /^(Anterior|Siguiente)$/ }).count(), 0)
  await screenshot('control-unidad-empty')
  console.log('PASS Control UI: header-only scope, filters payload, chips/badges, signed values, Lima, Eye, sticky table, three themes, empty without pagination')
  await headerSites().getByRole('button', { name: 'Casua', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.admin-site-context button[aria-pressed="true"]').textContent === 'Casua')
  await page.getByText('Grupo 99', { exact: true }).waitFor()
  assert.equal(calls.filter(c => c.action === 'control_groups').at(-1).payload.site_id, 'site-0')
  await headerSites().getByRole('button', { name: 'Huaca', exact: true }).click()
  await nav('Dashboard')
  assert.equal(await headerSites().count(), 0)
  await nav('Control')
  assert.equal(await headerSites().getByRole('button', { name: 'Huaca', exact: true }).getAttribute('aria-pressed'), 'true')

  if (controlOnly) {
    assert.deepEqual(errors, [])
    console.log(JSON.stringify({ status: 'PASS Control UI aislado', productionRequests: 0, rpcCalls: calls.length }))
  } else {
  await nav('Dispositivos')
  console.log('PASS Dashboard UI: cinco sedes, acordeón exclusivo/caché, cobertura válida/vacía, snapshot, 15 fechas/Lima, scroll tablet, tres temas y header global')
  await page.getByRole('heading', { name: 'Tablets por sede', exact: true }).waitFor()
  assert.equal(await page.locator('.admin-header').getByText('Puerto Rico', { exact: true }).count(), 0)
  const logo = page.locator('.admin-header').getByRole('img', { name: 'Puerto Rico', exact: true })
  assert.equal(await logo.getAttribute('src'), '/logo-pr-light.png')
  await logo.evaluate(image => image.decode())
  const logoSize = await logo.evaluate(image => ({ width: image.getBoundingClientRect().width, height: image.getBoundingClientRect().height, ratio: image.naturalWidth / image.naturalHeight, interactive: !!image.closest('button, a') }))
  assert.ok(logoSize.height >= 24 && logoSize.height <= 30)
  assert.ok(Math.abs(logoSize.width / logoSize.height - logoSize.ratio) < .01)
  assert.equal(logoSize.interactive, false)
  assert.equal(await page.locator('.admin-header').getByRole('button').count(), 0)
  assert.equal(await page.locator('.admin-devices select').count(), 0)
  assert.equal(await page.locator('.admin-devices').getByRole('button', { name: /Actualizar/ }).count(), 0)
  assert.deepEqual(await page.locator('[aria-labelledby="admin-tablets-title"] h3').allTextContents(), ['Cutervo', 'Huaca', 'Divino', 'Unidad', 'Casua'])
  assert.equal(await page.getByRole('article', { name: 'Tablet de Divino', exact: true }).getByText('No hay tablet autorizada.').count(), 1)
  assert.equal(await page.getByRole('article', { name: 'Solicitud de Huaca', exact: true }).getByRole('button', { name: 'Reemplazar tablet', exact: true }).count(), 1)
  assert.equal(await page.getByRole('article', { name: 'Solicitud de Huaca', exact: true }).getByRole('button', { name: 'Autorizar', exact: true }).count(), 0)
  assert.equal(await page.getByRole('article', { name: 'Solicitud de Divino', exact: true }).getByRole('button', { name: 'Autorizar', exact: true }).count(), 1)
  const card = page.getByRole('article', { name: 'Tablet de Cutervo', exact: true })
  assert.match(await card.innerText(), /Último acceso · Hoy,/)
  assert.equal(await page.locator('.admin-device-card--authorized').getByText(/Cajero/).count(), 0)
  assert.equal(await page.getByRole('article', { name: 'Solicitud de Huaca', exact: true }).getByText('Cajero Huaca', { exact: true }).count(), 1)
  assert.equal(await card.locator('.lucide-shield-off').count(), 1)
  const cardsText = await page.locator('.admin-devices').innerText()
  assert.equal(/84f12648|ID ·|Copiar|revisión/i.test(cardsText), false)
  assert.equal(await page.locator('.admin-devices .lucide-tablet').count(), 7)
  const themeSurfaces = []
  const beforeThemes = calls.length
  for (const [name, palette, icon] of [['Órbita', 'blue', 'orbit'], ['Prisma', 'violet', 'gem'], ['Natura', 'green', 'leaf']]) {
    const button = page.getByRole('button', { name, exact: true })
    assert.equal(await button.locator('.lucide-' + icon).count(), 1)
    await button.click()
    assert.equal(await button.getAttribute('aria-pressed'), 'true')
    themeSurfaces.push(await page.evaluate(() => {
      const bg = selector => getComputedStyle(document.querySelector(selector)).backgroundColor
      const style = selector => getComputedStyle(document.querySelector(selector))
      return { sidebar: bg('.admin-sidebar'), header: style('.admin-header').backgroundImage, title: style('.admin-header h1').color, panel: bg('.admin-v2-workspace'), card: bg('.admin-device-card'), badge: bg('.admin-device-badge--authorized'), accent: style('.admin-device-card__icon').color, revoke: bg('.admin-device-revoke'), revokeColor: style('.admin-device-revoke').color }
    }))
    await screenshot('expanded-' + palette)
  }
  for (const surface of ['sidebar', 'header', 'title', 'panel', 'card', 'badge', 'revoke', 'revokeColor']) assert.equal(new Set(themeSurfaces.map(theme => theme[surface])).size, 1)
  assert.equal(new Set(themeSurfaces.map(theme => theme.accent)).size, 3)
  assert.match(themeSurfaces[0].header, /linear-gradient/)
  assert.equal(themeSurfaces[0].title, 'rgb(248, 250, 252)')
  assert.equal(themeSurfaces[0].revoke, 'rgb(255, 240, 245)')
  assert.ok(themeSurfaces.every(theme => theme.card === 'rgb(255, 255, 255)' && theme.badge === themeSurfaces[0].badge))
  assert.equal(calls.length, beforeThemes)
  assert.equal(await page.locator('.admin-sidebar .lucide-palette, .admin-sidebar details, .admin-appearance .palette-option').count(), 0)
  assert.equal(await page.locator('.admin-site-context--global').count(), 0)
  const globalContext = logo
  const contextStyle = () => globalContext.evaluate(node => {
    const style = getComputedStyle(node)
    return [style.cursor, style.backgroundColor, style.boxShadow, style.borderTopWidth, style.filter]
  })
  const beforeHover = await contextStyle()
  await globalContext.hover()
  assert.deepEqual(await contextStyle(), beforeHover)
  assert.ok(['auto', 'default'].includes(beforeHover[0]))
  assert.equal(beforeHover[1], 'rgba(0, 0, 0, 0)')
  assert.equal(beforeHover[2], 'none')
  assert.equal(beforeHover[3], '0px')
  assert.equal(beforeHover[4], 'none')
  assert.equal(count('list'), 1)
  await screenshot('desktop')
  const revoke = card.getByRole('button', { name: 'Revocar', exact: true })
  await revoke.hover()
  await page.waitForFunction(() => getComputedStyle(document.querySelector('.admin-device-revoke')).backgroundColor !== 'rgb(255, 240, 245)')
  assert.equal(await revoke.evaluate(node => getComputedStyle(node).backgroundImage), 'none')
  await screenshot('revoke-hover')
  await logo.hover()
  const singleColumn = async () => {
    const boxes = await page.locator('[aria-labelledby="admin-tablets-title"] article').evaluateAll(cards => cards.map(card => { const r = card.getBoundingClientRect(); return { x: r.x, width: r.width, top: r.top, bottom: r.bottom } }))
    assert.ok(boxes.every((box, i) => box.x === boxes[0].x && box.width === boxes[0].width && (!i || box.top >= boxes[i - 1].bottom)))
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  }
  await singleColumn()
  await page.getByRole('button', { name: 'Alternar navegación' }).click()
  await page.waitForFunction(() => document.querySelector('.admin-sidebar').getBoundingClientRect().width <= 72)
  const appearance = page.getByRole('region', { name: 'Apariencia' })
  assert.equal(await appearance.getByRole('button').count(), 3)
  assert.deepEqual(await appearance.getByRole('button').allTextContents(), ['', '', ''])
  assert.deepEqual(await appearance.locator('svg').evaluateAll(icons => icons.map(icon => icon.getAttribute('class').split(' ').find(name => ['lucide-orbit', 'lucide-gem', 'lucide-leaf'].includes(name)))), ['lucide-orbit', 'lucide-gem', 'lucide-leaf'])
  const iconBoxes = await appearance.getByRole('button').evaluateAll(buttons => buttons.map(button => { const r = button.getBoundingClientRect(); return { x: r.x, top: r.top, bottom: r.bottom } }))
  assert.ok(iconBoxes.every((box, i) => box.x === iconBoxes[0].x && (!i || box.top >= iconBoxes[i - 1].bottom)))
  assert.equal(await appearance.evaluate(node => getComputedStyle(node).borderTopStyle), 'solid')
  assert.equal(await page.locator('.admin-sidebar__collapse').evaluate(node => getComputedStyle(node).borderTopStyle), 'solid')
  assert.equal(await page.locator('.admin-sidebar details, .admin-sidebar .lucide-palette').count(), 0)
  await page.getByRole('button', { name: 'Prisma', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'Prisma', exact: true }).getAttribute('title'), 'Prisma')
  assert.equal(await page.getByRole('button', { name: 'Prisma', exact: true }).getAttribute('aria-pressed'), 'true')
  assert.equal(await page.evaluate(() => document.documentElement.dataset.palette), 'violet')
  await screenshot('collapsed')
  await page.setViewportSize({ width: 820, height: 1180 })
  await singleColumn()
  await screenshot('tablet-collapsed')
  await page.getByRole('button', { name: 'Alternar navegación' }).click()
  await page.waitForFunction(() => document.querySelector('.admin-sidebar').getBoundingClientRect().width >= 190)
  await singleColumn()
  await screenshot('tablet-expanded')
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole('button', { name: 'Órbita', exact: true }).click()
  await page.getByRole('article', { name: 'Solicitud de Divino', exact: true }).getByRole('button', { name: 'Autorizar', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar autorizar' }).click()
  await page.waitForFunction(() => document.querySelector('.admin-dialog .button')?.disabled)
  assert.equal(await page.getByRole('button', { name: 'Confirmar autorizar' }).isDisabled(), true)
  assert.equal(await page.getByRole('article', { name: 'Solicitud de Huaca', exact: true }).getByRole('button', { name: 'Reemplazar tablet' }).isDisabled(), true)
  assert.equal(count('authorize'), 1)
  heldMutation()
  await page.getByRole('dialog').waitFor({ state: 'detached' })
  await page.getByRole('article', { name: 'Tablet de Divino', exact: true }).getByText('Autorizado', { exact: true }).waitFor()
  assert.equal(count('list'), 2)
  await nav('Catálogo'); await page.getByRole('button', { name: 'Ver propuesta' }).waitFor()
  await nav('Grupos'); await page.getByRole('heading', { name: 'Bebidas agrupadas' }).waitFor()
  await nav('Incidencias'); await page.getByRole('button', { name: /Ver repeticiones/ }).waitFor()
  await nav('Dispositivos'); await page.getByRole('heading', { name: 'Tablets por sede' }).waitFor()
  assert.equal(count('list'), 2)
  devices = devices.filter(d => d.estado === 'autorizado')
  failList = true
  await page.reload()
  await page.locator('.admin-devices').getByRole('button', { name: 'Reintentar lectura', exact: true }).click()
  await page.getByText('No hay solicitudes pendientes.').waitFor()
  assert.ok((await page.locator('.admin-devices__empty').boundingBox()).height < 50)
  assert.equal(await page.locator('.admin-devices__empty').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)')
  await screenshot('empty')
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ ok: true, scenarios: ['sites/order/alias/scope', 'themes/persistence', 'navigation/cache', 'global devices', 'single-column desktop/tablet', 'theme surfaces / semantic badges / no technical data', 'authorize/pending guard', 'read retry', 'empty requests'], rpcCalls: calls.length, productionRequests: 0, errors }, null, 2))
  }
} finally { if (heldMutation) heldMutation(); if (releaseControlRead) releaseControlRead(); await browser.close(); await server.close() }
