import { describe, expect, test } from 'bun:test'

async function source(path: string) {
  return Bun.file(path).text()
}

describe('AdminDialog Fase 8 — Drawers', () => {
  test('AdminDialog controla el ancho de drawer sin crear variantes nuevas', async () => {
    const dialog = await source('src/features/solog/admin/admin.dialog.tsx')
    const css = await source('src/features/solog/admin/admin.css')

    expect(dialog).toContain("export type AdminDialogVariant = 'default' | 'wide' | 'drawer'")
    expect(dialog).toContain('drawerMaxWidth?: number')
    expect(dialog).toContain('--admin-dialog-drawer-max-width')
    expect(css).toContain('width: min(calc(100% - 48px), var(--admin-dialog-drawer-max-width, 960px));')
    expect(css).toContain('.admin-dialog--wide,\n  .admin-dialog--drawer {\n    width: 100%;')
    expect(css).toContain('opacity var(--transition-fast)')
    expect(css).toContain('transform var(--transition-fast)')
    expect(css).toContain('.admin-dialog-backdrop--drawer.is-open')
    expect(css).toContain('transform: translateX(100%)')
    expect(css).toContain('.admin-dialog-backdrop--drawer.is-open .admin-dialog--drawer')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(dialog).toContain("const [drawerOpen, setDrawerOpen] = useState(variant !== 'drawer')")
    expect(dialog).toContain('requestAnimationFrame(() => setDrawerOpen(true))')
    expect(dialog).toContain('closeRequestedRef.current = true')
    expect(dialog).toContain("event.propertyName === 'transform'")
    expect(dialog).toContain('completeDrawerClose()')
  })

  test('Detalle diario separa Stock positivo/Stock 0 y usa StateViews', async () => {
    const dashboard = await source('src/features/solog/admin/dashboard/admin.dashboard.v2.tsx')
    const contract = await source('src/features/solog/admin/admin.v2.ts')
    const migration = await source('supabase/migrations/20260921184418_solog_admin_drawers_8_2b_daily_detail_v1.sql')

    expect(dashboard).toContain('drawerMaxWidth={620}')
    expect(dashboard).toContain('Stock positivo')
    expect(dashboard).toContain('Stock 0')
    expect(dashboard).toContain('role="tablist"')
    expect(dashboard).toContain('{ state: "Coincide", label: "Coincide" }')
    expect(dashboard).toContain('{ state: "Confirmada", label: "Confirmados" }')
    expect(dashboard).toContain('selectedState === "Coincide"')
    expect(dashboard).toContain('>Stock</th>')
    expect(dashboard).toContain('{ state: "Recontar", label: "Recontar" }')
    expect(dashboard).toContain('DAILY_DETAIL_PAGE_SIZE = 25')
    expect(dashboard).toContain('>Diferencias</th>')
    expect(dashboard).toContain('className="admin-difference-flow"')
    expect(dashboard).toContain('<DailySignedValue value={row.initial_difference} />')
    expect(dashboard).toContain('<DailySignedValue value={row.found_difference} />')
    expect(dashboard).not.toContain('value={-row.difference}')
    expect(dashboard).toContain('className="admin-dialog__footer-summary"')
    expect(dashboard).toContain('useAdminQuery("daily_detail_bootstrap"')
    expect(dashboard).toContain('"daily_detail_page"')
    expect(contract).toContain('export interface DailyDetailBootstrap')
    expect(contract).toContain('initial_difference: number; found_difference: number')
    expect(migration).toContain("daily_detail_bootstrap")
  })

  test('Cronología usa timeline y carga la quincena anterior solo al activar el switch', async () => {
    const control = await source('src/features/solog/admin/control/admin.control.v2.tsx')
    const context = await source('src/features/solog/admin/admin.v2.context.tsx')
    const css = await source('src/features/solog/admin/admin.css')

    expect(control).toContain('className="admin-control-chronology__timeline"')
    expect(control).toContain('className="admin-control-chronology__date-marker"')
    expect(control).toContain('if (row.state === "Coincide")')
    expect(control).toContain('if (row.state === "Confirmada")')
    expect(control).toContain('if (row.state === "Inconsistente")')
    expect(control).toContain('value: row.initial_difference')
    expect(control).toContain('value: row.found_difference')
    expect(control).not.toContain('value: -row.difference')
    expect(control).not.toContain('admin-control-chronology__valuation')
    expect(control).toContain('title={`Cronología por producto · ${siteName}`}')
    expect(control).toContain('className="admin-drawer-entity-summary"')
    expect(control).toContain('className={index === 0 ? "is-latest" : undefined}')
    expect(control).toContain('data-tone={tone}')
    expect(control).toContain('Incluir quincena anterior')
    expect(control).toContain('role="switch"')
    expect(control).toContain('{ enabled: showPrevious }')
    expect(control).toContain('useAdminQuery("control_chronology_view"')
    expect(control).toContain('currentData?.group.latest_unit_price')
    expect(control).toContain('drawerMaxWidth={560}')
    expect(control).not.toContain('admin-control-chronology__table')
    expect(context).toContain('options: { enabled?: boolean } = {}')
    expect(css).not.toContain('max-height: 60vh')
    expect(css).toContain('/* Fase 8.2A V2 — Drawers: composición compacta para validación visual. */')
    expect(css).toContain('.admin-control-chronology__event > article.is-latest')
    expect(css).toContain('.admin-difference--negative,')
    expect(css).not.toContain('.admin-v2-card section {\n  margin-top: 1rem;\n}')
    expect(css).not.toContain('.admin-v2-card header,')
    expect(css).toContain('.admin-v2-card > header,')
  })

  test('Repeticiones consume detalle agregado por sede sin paginación ni tabla', async () => {
    const incidents = await source('src/features/solog/admin/incidencias/admin.incidencias.v2.tsx')
    const management = await source('src/features/solog/admin/admin.management.v2.ts')
    const migration = await source('supabase/migrations/20260920211759_solog_admin_drawers_phase8_incident_detail_sites_v1.sql')

    expect(incidents).toContain('useManagementQuery("detail_sites"')
    expect(incidents).toContain('drawerMaxWidth={520}')
    expect(incidents).toContain('className="admin-incidents__site-repetitions"')
    expect(incidents).toContain('Sin registros')
    expect(incidents).toContain('className="admin-incidents__site-range"')
    expect(incidents).toContain('className="admin-drawer-entity-summary"')
    expect(incidents).toContain('className="admin-dialog__footer-actions admin-incidents__detail-actions"')
    expect(incidents).toContain('Ignorar 30 días')
    expect(incidents).toContain('Aprobar eliminación')
    expect(incidents).toContain('Reactivar incidencia')
    expect(incidents).toContain('family.family_state === "suprimida"')
    expect(incidents).toContain('family.active_suppression_until !== null')
    expect(incidents).toContain('.then(() => setDetailFamily(null))')
    expect(incidents).toContain('useManagementQuery(\n    "detail"')
    expect(incidents).toContain('legacyFallback')
    expect(incidents).not.toContain('admin-incidents__detail-table')
    expect(management).toContain('detail_sites:')
    expect(migration).toContain("p_action='detail_sites'")
  })
})
