import { describe, expect, test } from 'bun:test'
import { AdminStore } from '../src/features/solog/admin/admin.v2.store'
import { validateAdminResponse, type adminRpc, type AdminAction } from '../src/features/solog/admin/admin.v2'
import { validCustomRange } from '../src/features/solog/admin/admin.v2.format'
import { buildAdminWorkbook } from '../src/features/solog/admin/control/admin.control.v2.export'
// @ts-expect-error shared JS fixture for browser and unit tests
import { responseFixture, exportFixture, bootstrapFixture } from './fixtures/admin-v2.mjs'
function setup(handler = responseFixture) { const calls: [AdminAction, unknown][] = []; const rpc = (async (action, payload) => { calls.push([action,payload]); return handler(action,payload) }) as typeof adminRpc; return { store: new AdminStore('admin-test',rpc), calls } }
const page = { site_id: 'site-a', period: 'today' as const, state: null, page: 0, page_size: 100 }
describe('A1 store administrativo v2', () => {
  test('bootstrap mínimo, deduplicado, sin datasets de módulos', async () => { const {store,calls}=setup(); await Promise.all([store.load('bootstrap',{}),store.load('bootstrap',{})]); await store.load('bootstrap',{}); expect(calls).toEqual([['bootstrap',{}]]); expect(store.bootstrap?.identity.rol).toBe('admin') })
  test('admin y moderador desde identidad backend, no metadata cliente', async () => { const {store}=setup(() => bootstrapFixture('moderador')); await store.load('bootstrap',{}); expect(store.bootstrap?.permissions.can_admin).toBe(false) })
  test('rechaza identidad cruzada y sede no permitida', async () => { const {store}=setup(); await expect(store.load('control_page',page)).rejects.toThrow(); await store.load('bootstrap',{}); await expect(store.load('shift_grid',{site_id:'other'})).rejects.toThrow(); const s=new AdminStore('other', (async () => bootstrapFixture()) as typeof adminRpc); await expect(s.load('bootstrap',{})).rejects.toThrow('Identidad') })
  test('cache de módulo/sede/filtros persiste al regresar; no N+1', async () => { const {store,calls}=setup(); await store.load('bootstrap',{}); await store.load('dashboard_cards',{}); await store.load('control_page',page); await store.load('dashboard_cards',{}); await store.load('control_page',page); expect(calls).toHaveLength(3); await store.load('control_page',{...page,site_id:'site-b'}); expect(calls).toHaveLength(4) })
  test('refresh y salida descartan datos y respuestas pendientes', async () => { let resolve!: (v: unknown)=>void; const {store}=setup((a: string,p: unknown) => a==='bootstrap'?responseFixture(a,p):new Promise(r=>{resolve=r})); await store.load('bootstrap',{}); const pending=store.load('control_page',page); store.refresh(); resolve(responseFixture('control_page',page)); await expect(pending).rejects.toThrow('descartada'); expect(store.peek('control_page',page).data).toBeUndefined(); store.dispose(); await expect(store.load('bootstrap',{})).rejects.toThrow() })
  test('revisión operacional invalida solo sede afectada y cards; rechaza anteriores', async () => { let revision=10; const {store}=setup((a:string,p:unknown) => {const r=responseFixture(a,p); if(a==='daily_detail')r.revisions.operational=revision; return r}); await store.load('bootstrap',{}); await store.load('control_page',page); await store.load('control_page',{...page,site_id:'site-b'}); revision=11; await store.load('daily_detail',{site_id:'site-a',origin_date:'2026-09-03'}); expect(store.peek('control_page',page).data).toBeUndefined(); expect(store.peek('control_page',{...page,site_id:'site-b'}).data).toBeDefined(); await expect(store.load('control_page',page)).rejects.toThrow('anterior') })
  test('errores de autorización eliminan todo el estado operativo', async () => {const {store}=setup((a:string,p:unknown)=>{if(a==='control_page')throw Object.assign(new Error('Acceso revocado'),{code:'SOLOG_ADMIN_ROLE_REQUIRED'}); return responseFixture(a,p)});await store.load('bootstrap',{});await store.load('dashboard_cards',{});await expect(store.load('control_page',page)).rejects.toThrow();expect(store.bootstrap).toBeNull();expect(store.peek('dashboard_cards',{}).data).toBeUndefined()})
})
describe('A2 contratos y proyección autoritativa V5', () => {
  test('payload grid incluye sede y admite default y ambas quincenas', async () => {const {store,calls}=setup();await store.load('bootstrap',{}); for(const period of [undefined,'current_biweekly','previous_biweekly'] as const){const payload={site_id:'site-a',...(period?{period}:{})};const r=await store.load('shift_grid',payload);expect(r.data.totals[0].percentage).toBe(30);expect(calls.at(-1)).toEqual(['shift_grid',payload])}})
  test('conserva Total distinto de suma de turnos y cero de otra sede', () => {const a=validateAdminResponse('shift_grid',responseFixture('shift_grid',{site_id:'site-a'}));const b=validateAdminResponse('shift_grid',responseFixture('shift_grid',{site_id:'site-b'}));expect(a.data.shifts.map(r=>r.percentage)).toEqual([20,20,20]);expect(a.data.totals[0].percentage).toBe(30);expect(b.data.totals[0].numerator).toBe(0);expect(b.data.totals).toHaveLength(1)})
  test('detalle diario se solicita una sola vez por sede/origen/revisión', async () => {const {store,calls}=setup();await store.load('bootstrap',{});const p={site_id:'site-a',origin_date:'2026-09-03'};await store.load('daily_detail',p);await store.load('daily_detail',p);expect(calls.filter(c=>c[0]==='daily_detail')).toHaveLength(1)})
  test('rechaza wrapper genérico, versión y scope incorrectos', async () => {expect(()=>validateAdminResponse('shift_grid',{data:responseFixture('shift_grid')})).toThrow();expect(()=>validateAdminResponse('bootstrap',{...bootstrapFixture(),contract_version:5})).toThrow();const {store}=setup((a:string,p:unknown)=>a==='shift_grid'?responseFixture(a,{site_id:'site-b'}):responseFixture(a,p));await store.load('bootstrap',{});await expect(store.load('shift_grid',{site_id:'site-a'})).rejects.toThrow('otra sede')})
})
describe('A3 Control y Excel', () => {
  test('páginas 100+1, detalle bajo demanda y cache separado', async () => {const {store,calls}=setup();await store.load('bootstrap',{});expect((await store.load('control_page',page)).items).toHaveLength(100);expect((await store.load('control_page',{...page,page:1})).items).toHaveLength(1);expect(calls.some(c=>c[0]==='control_detail')).toBe(false);const p={site_id:'site-a',group_id:'group-0'};await store.load('control_detail',p);await store.load('control_detail',p);expect(calls.filter(c=>c[0]==='control_detail')).toHaveLength(1)})
  test('custom permite 92 días y rechaza rango inválido o superior', () => {expect(validCustomRange('2026-01-01','2026-04-02')).toBe(true);expect(validCustomRange('2026-01-01','2026-04-03')).toBe(false);expect(validCustomRange('2026-02-30','2026-03-02')).toBe(false);expect(validCustomRange('2026-09-03','2026-09-02')).toBe(false)})
  test('cada export es autoritativa bajo demanda, sin operation_id', async () => {const {store,calls}=setup();await store.load('bootstrap',{});const p={site_id:'site-a',period:'previous_biweekly' as const};await store.load('export',p);await store.load('export',p);expect(calls.filter(c=>c[0]==='export')).toEqual([['export',p],['export',p]])})
  test('cinco hojas, datos recibidos sin reselección ni valorización de inconsistentes', () => {const raw=exportFixture();const w=buildAdminWorkbook(raw);expect(w.sheets).toEqual(['Resumen','Ajustes','Por recontar','Inconsistentes','Todas']);const headers=w.data[3][0].map((c:unknown)=>(c as {value:unknown}).value);expect(headers).not.toContain('Valorizado (S/)');expect(headers).not.toContain('Stock posterior');expect(headers).toContain('Teórico de reconteo');expect(w.data[1]).toHaveLength(raw.adjustments.length+1);expect(w.data[1][1][6]).toMatchObject({value:-2});raw.adjustments=[];expect(buildAdminWorkbook(raw).data[1]).toHaveLength(1)})
})
