// A1–A3 against simulated Auth/RPC only; production requests are blocked.
import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'
import { createServer } from 'vite'
import { adminNow, responseFixture } from './fixtures/admin-v2.mjs'
const require = createRequire(import.meta.url)
const { unzipSync, strFromU8 } = createRequire(require.resolve('write-excel-file/package.json'))('fflate')
export async function runAdminV2Browser() {
  const { chromium } = await import(pathToFileURL(process.env.SOLOG_PLAYWRIGHT_MODULE).href)
  const server = await createServer({ server: { host: '127.0.0.1', port: 5208, strictPort: true }, define: {
    'import.meta.env.VITE_SUPABASE_URL': JSON.stringify('https://solog-admin-v2.test'),
    'import.meta.env.VITE_SUPABASE_ANON_KEY': JSON.stringify('test-only-anon-key'),
  } })
  await server.listen()
  const browser = await chromium.launch({ headless: true, executablePath: process.env.SOLOG_TEST_BROWSER })
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, timezoneId: 'Asia/Tokyo' })
  const user = { id: 'admin-test', email: 'admin@example.test', role: 'authenticated', app_metadata: {}, user_metadata: { rol: 'cajero' }, aud: 'authenticated', created_at: adminNow }
  const exp = Math.floor(Date.now()/1000)+3600
  const jwt = [{alg:'HS256',typ:'JWT'},{sub:user.id,aud:'authenticated',role:'authenticated',exp}].map(p=>Buffer.from(JSON.stringify(p)).toString('base64url')).join('.')+'.test'
  await context.addInitScript(({user,jwt,exp})=>localStorage.setItem('sb-solog-admin-v2-auth-token',JSON.stringify({access_token:jwt,refresh_token:'test',expires_at:exp,expires_in:3600,token_type:'bearer',user})),{user,jwt,exp})
  const calls=[], errors=[]
  let bytes=0, empty=false, denied=false, revision=10, failPrevious=true
  const count=a=>calls.filter(c=>c.action===a).length
  await context.route('**/*', async route=>{
    const url=new URL(route.request().url())
    if(url.hostname==='127.0.0.1')return route.continue()
    if(url.hostname!=='solog-admin-v2.test'){errors.push('Unexpected external '+url.hostname);return route.abort()}
    const fulfill=(data,status=200)=>{const body=JSON.stringify(data);bytes+=Buffer.byteLength(body);return route.fulfill({status,contentType:'application/json',body})}
    if(url.pathname==='/auth/v1/user')return fulfill(user)
    if(url.pathname==='/auth/v1/logout')return fulfill({})
    const rpc=url.pathname.split('/').at(-1), body=route.request().postDataJSON()
    assert.ok(['rpc_solog_admin_bootstrap_v2','rpc_solog_operational_v2','rpc_solog_control_export_v2'].includes(rpc),'No v1 or other modules: '+rpc)
    const action=rpc==='rpc_solog_admin_bootstrap_v2'?'bootstrap':rpc==='rpc_solog_control_export_v2'?'export':body.p_action
    const p=body.p_payload;calls.push({rpc,action,payload:p})
    if(action==='bootstrap'||action==='dashboard_cards')assert.deepEqual(p,{})
    if(action==='shift_grid')assert.deepEqual(Object.keys(p).sort(),['period','site_id'])
    if(action==='control_groups')assert.deepEqual(Object.keys(p).sort(),p.period==='custom'?['date_from','date_to','period','site_id']:['period','site_id'])
    if(action==='control_chronology')assert.deepEqual(Object.keys(p).sort(),['group_id','period','site_id'])
    assert.ok(!['control_page','control_detail'].includes(action),'No legacy Control calls')
    if(action==='export')assert.deepEqual(Object.keys(p).sort(),['period','site_id'])
    if(denied)return fulfill({code:'P0001',message:'SOLOG_ADMIN_ROLE_REQUIRED'},400)
    if(action==='control_chronology'&&p.period==='previous_biweekly'&&failPrevious){failPrevious=false;return fulfill({message:'Lectura de quincena fallida',code:'500'},500)}
    const response=responseFixture(action,p)
    if(action==='control_chronology') {
      if(p.period==='previous_biweekly') response.chronology=[]
      else response.chronology.unshift(
        {row_id:'single-match',case_id:'single-match',event_at:'2026-09-01T08:58:00Z',state:'Coincide',theoretical:10,physical:10,difference:0,valued_difference:0,valuation:{unit_price:42,units_per_package:null,package_price:null}},
        {row_id:'single-pending',case_id:'single-pending',event_at:'2026-09-02T08:58:00Z',state:'Recontar',theoretical:10,physical:15,difference:5,valued_difference:210,valuation:{unit_price:42,units_per_package:null,package_price:null}},
      )
    }
    if(response.revisions.operational!==undefined)response.revisions.operational=revision
    if(action==='bootstrap')response.allowed_sites.forEach(s=>s.operational_revision=revision)
    if(action==='dashboard_cards')response.sites.forEach(s=>s.operational_revision=revision)
    if(action==='export'&&empty){for(const key of ['adjustments','pending_recount','inconsistent','all'])response[key]=[];for(const key of Object.keys(response.summary))response.summary[key]=0}
    return fulfill(response)
  })
  const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message))
  try {
    const controlOnly = process.env.SOLOG_CONTROL_UI_ONLY === '1'
    await page.goto('http://127.0.0.1:5208/admin' + (controlOnly ? '/control' : ''))
    if (!controlOnly) {
    await page.getByRole('heading',{name:'Sede A',exact:true}).waitFor()
    assert.equal(count('bootstrap'),1);assert.equal(count('dashboard_cards'),1);assert.equal(calls.length,2)
    assert.equal(await page.getByRole('progressbar').count(),2)
    await page.getByText('Quincena completada',{exact:true}).waitFor()
    await page.getByText('Sin snapshot confirmado',{exact:false}).waitFor()
    let resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(r=>r.name))
    assert.equal(resources.some(u=>/admin\.control\.v2\.tsx|admin\.catalogo|admin\.grupos|admin\.incidencias|admin\.dispositivos|write-excel-file/.test(u)),false)
    await page.getByRole('button',{name:'Ver turnos de Sede A'}).click()
    await page.getByRole('button',{name:'Abrir día 2026-09-03'}).waitFor()
    assert.equal(count('shift_grid'),1);assert.equal(count('daily_detail'),0)
    assert.match(await page.locator('tr').filter({has:page.locator('th',{hasText:'Total'})}).innerText(),/30%/)
    await page.getByRole('button',{name:'Abrir día 2026-09-03'}).click()
    await page.getByRole('dialog').getByText('Grupo 0 · Confirmada').waitFor()
    await page.getByRole('button',{name:'Cerrar',exact:true}).click()
    await page.getByRole('button',{name:'Abrir día 2026-09-03'}).click()
    assert.equal(count('daily_detail'),1)
    await page.getByRole('button',{name:'Cerrar',exact:true}).click()
    await page.getByLabel('Quincena de turnos').selectOption('previous_biweekly')
    await page.getByRole('button',{name:'Abrir día 2026-08-31'}).waitFor()
    await page.getByLabel('Quincena de turnos').selectOption('current_biweekly')
    await page.getByRole('button',{name:'Abrir día 2026-09-03'}).waitFor()
    assert.equal(count('shift_grid'),2)
    await page.getByRole('button',{name:'Ver turnos de Sede B'}).click()
    const siteB=page.getByRole('article',{name:'Sede Sede B'})
    await siteB.getByRole('button',{name:'Abrir día 2026-09-03'}).waitFor()
    assert.equal(await page.getByRole('article',{name:'Sede Sede A'}).getByRole('table').count(),0)
    assert.equal(await page.locator('.admin-dashboard [aria-expanded="true"]').count(),1)
    assert.equal(await siteB.getByRole('columnheader',{name:'Jue 03',exact:true}).count(),1)
    assert.equal(await page.getByText(/Actualizado/).count(),0)
    assert.match(await siteB.locator('tr').filter({has:page.locator('th',{hasText:'Total'})}).innerText(),/0%/)
    await siteB.getByRole('button',{name:'Descargar ajuste',exact:true}).click()
    await page.getByRole('dialog').getByLabel('Período de exportación').waitFor()
    assert.equal(count('export'),0,'Abrir exportación no descarga automáticamente')
    await page.getByRole('button',{name:'Cerrar',exact:true}).click()
    if(process.env.SOLOG_ADMIN_SCREENSHOT)await page.screenshot({path:process.env.SOLOG_ADMIN_SCREENSHOT.replace('.png','-dashboard.png'),fullPage:true})
    }
    await page.getByRole('button',{name:'Control',exact:true}).click()
    const control=page.locator('.admin-control'), tableRows=control.locator('tbody tr')
    await page.getByText('Grupo 99',{exact:true}).waitFor()
    assert.equal(count('control_groups'),1);assert.equal(count('control_chronology'),0)
    assert.equal(await tableRows.count(),100)
    assert.equal(await control.getByLabel('Estado',{exact:true}).count(),0)
    assert.equal(await control.getByRole('button',{name:'Aplicar filtros'}).count(),0)
    const summary=await control.locator('.admin-control__chip').allTextContents()
    const countBase=count('control_groups')
    await page.getByRole('button',{name:'Siguiente',exact:true}).click()
    await page.getByText('Grupo 100',{exact:true}).waitFor()
    assert.equal(await tableRows.count(),1);assert.equal(count('control_groups'),countBase)
    await control.locator('.admin-control__chip').filter({hasText:'Recontar'}).click()
    assert.equal(await control.locator('.admin-control__pagination span').innerText(),'Página 1')
    assert.equal(await tableRows.count(),25)
    assert.ok((await control.locator('.admin-control__badge').allTextContents()).every(s=>s==='Por recontar'))
    assert.deepEqual(await control.locator('.admin-control__chip').allTextContents(),summary)
    await control.getByLabel('Buscar grupo').fill('  GRUPO 1 ')
    assert.deepEqual(await tableRows.locator('td:first-child').allTextContents(),['Grupo 1','Grupo 13','Grupo 17'])
    assert.deepEqual(await control.locator('.admin-control__chip').allTextContents(),summary)
    assert.equal(count('control_groups'),countBase)
    await control.getByLabel('Buscar grupo').fill('no existe')
    await control.getByText('No hay resultados para los filtros seleccionados.').waitFor()
    assert.equal(await control.getByRole('table').count(),0)
    assert.equal(await control.locator('.admin-control__pagination').count(),0)
    await control.getByLabel('Buscar grupo').fill('')
    await control.locator('.admin-control__chip').first().click()
    assert.equal(await tableRows.count(),100)
    assert.equal(count('control_groups'),countBase,'Local filters cannot reload same context')
    await control.getByRole('button',{name:'Siguiente',exact:true}).click()
    await control.getByLabel('Buscar grupo').fill('Grupo 100')
    assert.equal(await control.locator('.admin-control__pagination span').innerText(),'Página 1')
    assert.deepEqual(await tableRows.locator('td:first-child').allTextContents(),['Grupo 100'])
    await control.getByLabel('Buscar grupo').fill('')
    await control.getByRole('button',{name:'Siguiente',exact:true}).click()
    const selectPeriod=async label=>{await page.getByRole('combobox',{name:'Período',exact:true}).click();await page.getByRole('option',{name:label,exact:true}).click();await page.getByText('Grupo 99',{exact:true}).waitFor()}
    await selectPeriod('Período anterior quincenal')
    assert.equal(await control.locator('.admin-control__pagination span').innerText(),'Página 1')
    assert.equal(count('control_groups'),countBase+1)
    await page.getByRole('button',{name:'Ver cronología de Grupo 0',exact:true}).click()
    const dialog=page.getByRole('dialog')
    await dialog.getByRole('columnheader',{name:'Fecha',exact:true}).waitFor()
    const chronologyRows=await dialog.locator('tbody tr').evaluateAll(rows=>rows.map(row=>[...row.cells].map(c=>c.textContent)))
    assert.deepEqual(await dialog.getByRole('columnheader').allTextContents(),['Fecha','Hora','Estado','Teórico','Físico','Diferencia','Valorizado','Detalle'])
    assert.deepEqual(chronologyRows.map(r=>r.slice(2,6)),[['Coincide','10','10','0'],['Recontar','10','15','+5'],['Recontado','3','13','+10'],['Recontado','114','104','-10'],['Confirmada','3','8','+5'],['Inconsistente','114','119','+5']])
    assert.match(chronologyRows[0][0],/01 (set|sep)\./)
    assert.equal(chronologyRows[0][1],'3:58 am')
    assert.match(chronologyRows[3][7],/Unidades por paquete: 6/)
    assert.equal(await dialog.locator('tbody tr').first().locator('td').nth(6).evaluate(node=>getComputedStyle(node).textAlign),'right')
    assert.equal(await dialog.getByRole('columnheader',{name:/Origen|Estado vigente|Stock posterior|Diferencia inicial|Teórico de conteo/}).count(),0)
    const periods=dialog.getByRole('group',{name:'Quincena de cronología'})
    assert.equal(await periods.getByRole('button',{name:'Actual',exact:true}).getAttribute('aria-pressed'),'true')
    assert.equal(await periods.getByRole('button',{name:'Actual',exact:true}).evaluate(node=>node===document.activeElement),true)
    await page.keyboard.press('Shift+Tab')
    assert.equal(await dialog.getByRole('button',{name:'Cerrar',exact:true}).evaluate(node=>node===document.activeElement),true)
    await page.keyboard.press('Shift+Tab')
    assert.equal(await periods.getByRole('button',{name:'Anterior',exact:true}).evaluate(node=>node===document.activeElement),true)
    await page.keyboard.press('Tab')
    assert.equal(await dialog.getByRole('button',{name:'Cerrar',exact:true}).evaluate(node=>node===document.activeElement),true)
    if(process.env.SOLOG_ADMIN_SCREENSHOT)await page.screenshot({path:process.env.SOLOG_ADMIN_SCREENSHOT.replace('.png','-chronology.png'),fullPage:false})
    await page.setViewportSize({width:390,height:844})
    const modalBox=await dialog.boundingBox()
    assert.ok(modalBox.x>=0&&modalBox.x+modalBox.width<=390)
    assert.equal(await dialog.locator('.admin-control-chronology__table').evaluate(node=>node.scrollWidth>node.clientWidth),true)
    if(process.env.SOLOG_ADMIN_SCREENSHOT)await page.screenshot({path:process.env.SOLOG_ADMIN_SCREENSHOT.replace('.png','-chronology-mobile.png'),fullPage:false})
    await page.setViewportSize({width:1440,height:960})
    await periods.getByRole('button',{name:'Anterior',exact:true}).click()
    await dialog.getByRole('button',{name:'Reintentar',exact:true}).waitFor()
    assert.equal(await periods.getByRole('button',{name:'Actual',exact:true}).isVisible(),true)
    await dialog.getByRole('button',{name:'Reintentar',exact:true}).click()
    await dialog.getByText('No hay registros en esta quincena.',{exact:true}).waitFor()
    assert.equal(calls.filter(c=>c.action==='control_chronology').at(-1).payload.period,'previous_biweekly')
    const chronologyCalls=count('control_chronology')
    await periods.getByRole('button',{name:'Actual',exact:true}).click()
    await dialog.getByRole('columnheader',{name:'Fecha',exact:true}).waitFor()
    await periods.getByRole('button',{name:'Anterior',exact:true}).click()
    await dialog.getByText('No hay registros en esta quincena.',{exact:true}).waitFor()
    await periods.getByRole('button',{name:'Actual',exact:true}).click()
    assert.equal(count('control_chronology'),chronologyCalls,'Both biweekly scopes cached')
    assert.equal(await dialog.locator('tbody tr').count(),6)
    assert.deepEqual(calls.find(c=>c.action==='control_chronology').payload,{site_id:'site-a',group_id:'group-0',period:'current_biweekly'})
    await page.getByRole('button',{name:'Cerrar',exact:true}).click()
    await page.getByRole('button',{name:'Ver cronología de Grupo 0',exact:true}).click()
    await dialog.getByRole('columnheader',{name:'Fecha',exact:true}).waitFor()
    assert.equal(count('control_chronology'),3)
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog').count(),0)
    assert.equal(await page.getByRole('button',{name:'Ver cronología de Grupo 0',exact:true}).evaluate(node=>node===document.activeElement),true)
    await selectPeriod('Hoy')
    assert.equal(count('control_groups'),countBase+1,'Returning to cached period has no RPC')
    await page.getByRole('group',{name:'Sede administrativa'}).getByRole('button',{name:'Sede B',exact:true}).click()
    await page.getByText('Grupo 99',{exact:true}).waitFor()
    assert.equal(count('control_groups'),countBase+2)
    await page.getByRole('group',{name:'Sede administrativa'}).getByRole('button',{name:'Sede A',exact:true}).click()
    await page.getByText('Grupo 99',{exact:true}).waitFor()
    assert.equal(count('control_groups'),countBase+2,'Returning to cached site has no RPC')
    await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByRole('heading',{name:'Sede A',exact:true}).waitFor();assert.equal(count('dashboard_cards'),1)
    await page.getByRole('button',{name:'Control',exact:true}).click();await page.getByText('Grupo 99',{exact:true}).waitFor();assert.equal(count('control_groups'),countBase+2)
    await page.getByRole('combobox',{name:'Período',exact:true}).click();await page.getByRole('option',{name:'Personalizado',exact:true}).click();await page.getByLabel('Desde',{exact:true}).fill('2026-01-01');await page.getByLabel('Hasta',{exact:true}).fill('2026-05-01');await control.getByRole('alert').waitFor();assert.equal(count('control_groups'),countBase+2)
    await page.getByLabel('Hasta',{exact:true}).fill('2026-04-02');await page.getByRole('combobox',{name:'Período',exact:true}).filter({hasText:'01 ene. — 02 abr.'}).waitFor()
    assert.deepEqual(calls.filter(c=>c.action==='control_groups').at(-1).payload,{site_id:'site-a',period:'custom',date_from:'2026-01-01',date_to:'2026-04-02'})
    console.log('PASS V10 automatic UI: local state/search/pages; stable summary; context cache; independent Eye current_biweekly and authoritative rows; custom; empty')
    for(const period of ['current_biweekly','previous_biweekly']) {
      await page.getByRole('button',{name:'Descargar ajuste',exact:true}).click()
      await page.getByLabel('Período de exportación').selectOption(period)
      const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Descargar Excel'}).click()])
      const stream=await download.createReadStream(), chunks=[];for await(const chunk of stream)chunks.push(chunk)
      const zip=unzipSync(Buffer.concat(chunks));const xml=strFromU8(zip['xl/workbook.xml']);for(const name of ['Resumen','Ajustes','Por recontar','Inconsistentes','Todas'])assert.ok(xml.includes(name))
      const strings=strFromU8(zip['xl/sharedStrings.xml']);assert.ok(strings.includes('Teórico de reconteo'));assert.ok(strings.includes('Por recontar'))
      assert.ok(strFromU8(zip['xl/worksheets/sheet2.xml']).includes('<v>-2</v>'))
      const parsed=await page.evaluate(({strings,sheet})=>{
        const parse=t=>new DOMParser().parseFromString(t,'application/xml')
        const values=[...parse(strings).querySelectorAll('si')].map(n=>n.textContent)
        return [...parse(sheet).querySelector('row').querySelectorAll('c')].map(c=>c.getAttribute('t')==='s'?values[Number(c.querySelector('v').textContent)]:c.textContent)
      },{strings,sheet:strFromU8(zip['xl/worksheets/sheet4.xml'])})
      assert.deepEqual(parsed,['Grupo','Categoría','Fecha de origen','Teórico de conteo','Físico de conteo','Diferencia de conteo','Teórico de reconteo','Físico de reconteo','Diferencia de reconteo','Estado'])
      assert.match(download.suggestedFilename(),/SOLOG_Ajustes_Sede_A_/)
    }
    empty=true;await page.getByRole('button',{name:'Descargar ajuste',exact:true}).click();await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Descargar Excel'}).click()]);assert.equal(count('export'),3)
    assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.includes('admin-operational'))),false)
    revision++;await page.reload();await page.locator('.admin-control').waitFor();await page.getByText('Grupo 99',{exact:true}).waitFor();assert.equal(count('bootstrap'),2)
    await page.setViewportSize({width:800,height:900});await page.getByRole('button',{name:'Alternar navegación'}).click()
    await page.locator('.admin-control').scrollIntoViewIfNeeded()
    await page.waitForFunction(()=>document.querySelector('.admin-sidebar')?.getBoundingClientRect().width<=72)
    if(process.env.SOLOG_ADMIN_SCREENSHOT)await page.screenshot({path:process.env.SOLOG_ADMIN_SCREENSHOT,fullPage:false})
    denied=true;await page.reload();await page.getByRole('button',{name:'Reintentar',exact:true}).waitFor();assert.equal(await page.getByText('Grupo 99',{exact:true}).count(),0)
    assert.deepEqual(errors,[])
    console.log(JSON.stringify({status:controlOnly?'PASS Control/Excel browser simulado':'PASS A1–A3 browser simulado',rpcCalls:calls.length,responseBytes:bytes,productionCalls:0,actions:Object.fromEntries(['bootstrap','dashboard_cards','shift_grid','daily_detail','control_groups','control_chronology','export'].map(a=>[a,count(a)]))}))
  } finally {await browser.close();await server.close()}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)await runAdminV2Browser()
