import assert from 'node:assert/strict'

export const canonicalKeys = ['7', '8', '9', 'C', '4', '5', '6', '×', '1', '2', '3', '+', '0', 'x6', 'x12', '⌫']

export async function verifyReviewCapture(page, calls) {
  const before = calls.length
  await page.getByRole('button', { name: 'Revisar Grupo revisión', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const button = (name) => dialog.getByRole('button', { name, exact: true })
  const progress = async (n) => {
    assert.equal(await dialog.locator('.cajero-capture-modal__header > strong').textContent(), n + ' / 15')
    assert.equal(await dialog.locator('.cajero-capture-modal__progress > strong').textContent(), Math.round(n / 15 * 100) + '%')
  }
  assert.deepEqual(await dialog.locator('.cajero-calculator__keys button').allTextContents(), canonicalKeys)
  assert.equal(await button('Guardar').count(), 0)
  assert.equal(await button('Anterior').isDisabled(), true)
  assert.deepEqual(await dialog.locator('dt').allTextContents(), ['Stock TumiSoft', 'Conteo', 'Diferencia actual', 'Valorizado'])
  await progress(0)
  assert.equal(await button('Productos incluidos').count(), 0)
  for (let i = 0; i < 6; i++) await button('Siguiente').click()
  await dialog.getByRole('heading', { name: /Grupo revisión 7/ }).waitFor()
  await progress(0)
  const products = button('Productos incluidos')
  assert.equal(await products.getAttribute('aria-expanded'), 'false')
  await products.click()
  assert.deepEqual(await dialog.locator('.cajero-capture-products li').allTextContents(), ['Lemonade#20534', 'Cherry#20535'])
  assert.equal(await dialog.getByText('Marca oculta').count(), 0)
  await button('Siguiente').click()
  await button('Anterior').click()
  assert.equal(await products.getAttribute('aria-expanded'), 'false')
  await button('2').click()
  await button('Multiplicar por 6').click()
  assert.equal(await dialog.locator('.cajero-calculator__display strong').textContent(), '12')
  await button('Limpiar expresión').click()
  await button('2').click()
  await button('Multiplicar por 12').click()
  assert.equal(await dialog.locator('.cajero-calculator__display strong').textContent(), '24')
  const values = dialog.locator('.cajero-capture-detail__card dd')
  assert.equal(await values.nth(1).textContent(), '24')
  assert.equal(await values.nth(2).textContent(), '+14')
  assert.match(await values.nth(3).textContent(), /48[.,]00/)
  await progress(0)
  await button('Continuar').click()
  await dialog.getByRole('heading', { name: /Grupo revisión 8/ }).waitFor()
  await progress(1)
  await button('Anterior').click()
  await button('Siguiente').waitFor()
  await progress(1)
  await button('Limpiar expresión').click()
  await button('9').click()
  await button('Continuar').click()
  await progress(1)
  for (let i = 0; i < 7; i++) await button('Siguiente').click()
  await dialog.getByRole('heading', { name: /Grupo revisión 15/ }).waitFor()
  await progress(1)
  assert.equal(await button('Siguiente').isDisabled(), true)
  await button('1').click()
  await button('Continuar').click()
  await dialog.getByRole('heading', { name: /Grupo revisión 15/ }).waitFor()
  await progress(2)
  assert.equal(await button('Siguiente').isDisabled(), true)
  await button('Sumar').click()
  await button('1').click()
  await button('Continuar').click()
  await progress(2)
  assert.equal(await values.nth(1).textContent(), '2')
  await button('Anterior').click()
  await button('Siguiente').click()
  await progress(2)
  assert.equal(calls.length, before, 'Abrir, navegar, escribir, guardar y editar no generan requests')
  await button('Regresar').click()
  assert.equal(await page.getByRole('dialog').count(), 0)
  await page.getByRole('button', { name: 'Revisar Grupo revisión 7', exact: true }).click()
  await progress(2)
  assert.equal(await values.nth(1).textContent(), '9')
  await button('Cerrar').click()
  assert.equal(calls.length, before, 'Reabrir drafts no consulta backend')
}
