import { describe, expect, test } from 'bun:test'
import { CashierV4DraftStorage, cashierV4DraftStorageKey, CASHIER_V4_STORAGE_PREFIX } from '../src/features/solog/cajero/cajero.v4.storage'
import { draftHarness, memoryStorage, uuidFor } from './fixtures/cashier-v4-drafts'
import { cashierV4Ids as ids } from './fixtures/cashier-v4.mjs'

describe('Cajero 13.3: drafts y persistencia independiente', () => {
  test('scope incluye cinco campos y cada sesión/revisión tiene clave distinta', () => {
    const h = draftHarness()
    expect(h.scope).toEqual({ usuario_id: ids.user, sede_id: ids.site, dispositivo_id: ids.device, conteo_id: ids.session, groups_revision: 7 })
    expect(cashierV4DraftStorageKey(h.scope)).not.toBe(cashierV4DraftStorageKey({ ...h.scope, conteo_id: uuidFor(1) }))
    expect(cashierV4DraftStorageKey(h.scope)).not.toBe(cashierV4DraftStorageKey({ ...h.scope, groups_revision: 8 }))
  })
  test('normal conserva ID y timestamp al editar; reload conserva los mismos datos', () => {
    const h = draftHarness()
    const first = h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp }, { grupo: 'Arroz' })
    const second = h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 9, contado_at: new Date(Date.parse(h.stamp) + 1000).toISOString() })
    expect(second.client_observation_id).toBe(first.client_observation_id)
    expect(second.contado_at).toBe(first.contado_at)
    expect(new CashierV4DraftStorage(h.raw).read(h.scope).normal[0]).toEqual(second)
    expect(second.scope).toEqual(h.scope)
  })
  test('recount conserva timestamp y permanece separado del normal', () => {
    const h = draftHarness()
    h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp })
    const first = h.coordinator.captureRecount(h.scope, { grupo_id: ids.review, detalle_id: ids.detail, stock_fisico: 10, contado_at: h.stamp })
    const second = h.coordinator.captureRecount(h.scope, { grupo_id: ids.review, detalle_id: ids.detail, stock_fisico: 8, contado_at: new Date(Date.parse(h.stamp) + 1000).toISOString() })
    expect(second.contado_at).toBe(first.contado_at)
    const record = h.storage.read(h.scope)
    expect(record.normal).toHaveLength(1)
    expect(record.recount).toHaveLength(1)
    expect(record.recount[0].kind).toBe('recount')
  })
  test('snapshot persistido tiene colas originales y no capability', () => {
    const h = draftHarness()
    const record = h.coordinator.synchronize(h.scope)
    expect(record.delivery_state?.next_action).toBe('review')
    expect(record.delivery_state).not.toHaveProperty('session_capability')
    expect(record.delivery_state).not.toHaveProperty('groups')
  })
  test('active A → recovery + B preserva drafts, scope y snapshot A', () => {
    const h = draftHarness()
    const draft = h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp })
    h.moveToRecovery()
    h.coordinator.synchronize(h.scope)
    const record = h.storage.read(h.scope)
    expect(record.normal[0]).toEqual(draft)
    expect(record.delivery_state!.groups_revision).toBe(7)
    expect(h.coordinator.activeScope()!.groups_revision).toBe(99)
    expect(h.storage.hasPending(h.scope, h.scope.conteo_id)).toBe(true)
  })
  test('refresh mantiene prepared operation, draft y snapshot exactos', async () => {
    const h = draftHarness('coverage')
    h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp })
    h.respond(async () => { throw new Error('timeout') })
    await expect(h.coordinator.flush(h.scope)).rejects.toThrow('timeout')
    const before = h.storage.read(h.scope)
    h.store.acceptBootstrap(h.initial)
    h.coordinator.synchronize(h.scope)
    expect(h.storage.read(h.scope)).toEqual(before)
    expect(before.prepared!.operation_id).toBe(h.requests[0].payload.operation_id)
    expect(before.prepared).not.toHaveProperty('device_token')
  })
  test('payload preparado no puede editarse ni reemplazarse por otro UUID', async () => {
    const h = draftHarness('coverage')
    h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp })
    h.respond(async () => { throw new Error('timeout') })
    await expect(h.coordinator.flush(h.scope)).rejects.toThrow()
    const before = h.storage.read(h.scope)
    const altered = structuredClone(before)
    if (altered.prepared!.action !== 'finish') altered.prepared!.items[0].stock_fisico = 7
    expect(() => h.storage.write(altered)).toThrow()
    altered.prepared = { ...before.prepared!, operation_id: uuidFor(555) }
    expect(() => h.storage.write(altered)).toThrow()
    expect(() => h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 8, contado_at: h.stamp })).toThrow()
    expect(h.storage.read(h.scope)).toEqual(before)
  })
  test('recovery no crea capturas; drafts de B usan scope e ID propios', () => {
    const h = draftHarness()
    const a = h.coordinator.captureNormal(h.scope, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp })
    const b = h.moveToRecovery()
    expect(() => h.coordinator.captureNormal(h.scope, { grupo_id: ids.daily, stock_fisico: 0, contado_at: h.stamp })).toThrow()
    expect(() => h.coordinator.captureRecount(h.scope, { grupo_id: ids.review, detalle_id: ids.detail, stock_fisico: 10, contado_at: h.stamp })).toThrow()
    const scopeB = h.coordinator.activeScope()!
    const draftB = h.coordinator.captureNormal(scopeB, { grupo_id: ids.coverage, stock_fisico: 10, contado_at: b.panel_state!.session.iniciado_at })
    expect(draftB.scope.conteo_id).not.toBe(a.scope.conteo_id)
    expect(draftB.client_observation_id).not.toBe(a.client_observation_id)
    expect(h.storage.sessions(h.scope)).toHaveLength(2)
  })
  test('V3 y datos corruptos permanecen intactos; no hay migración destructiva', () => {
    const raw = memoryStorage()
    raw.setItem('solog.cajero.buffer.v4:legacy', '{"version":4}')
    const h = draftHarness()
    const key = cashierV4DraftStorageKey(h.scope)
    raw.setItem(key, '{broken')
    const storage = new CashierV4DraftStorage(raw)
    expect(() => storage.read(h.scope)).toThrow()
    expect(raw.getItem(key)).toBe('{broken')
    expect(raw.getItem('solog.cajero.buffer.v4:legacy')).toBe('{"version":4}')
    expect(CASHIER_V4_STORAGE_PREFIX).not.toMatch(/^solog\.cajero\.(buffer|expressions|recount|activity)\./)
  })
  test('rechaza scope ajeno, timestamps fuera de ventana y stock inválido', () => {
    const h = draftHarness()
    const input = { grupo_id: ids.coverage, stock_fisico: 10, contado_at: h.stamp }
    expect(() => h.coordinator.captureNormal({ ...h.scope, dispositivo_id: uuidFor(1) }, input)).toThrow()
    expect(() => h.coordinator.captureNormal(h.scope, { ...input, contado_at: '2025-01-01T00:00:00Z' })).toThrow()
    expect(() => h.coordinator.captureNormal(h.scope, { ...input, stock_fisico: -1 })).toThrow()
    expect(h.storage.read(h.scope).normal).toEqual([])
  })
})
