import { useState } from 'react'
import { AdminDialog } from '../admin.dialog'
import { useAdminStore } from '../admin.v2.context'
import { useManagement, useManagementQuery } from '../admin.management.context'
import type { ReadPayloads, Mutations } from '../admin.management.v2'
import type { CatalogChange as SologCatalogChangeRow } from '../admin.management.v2'
import { adminTimestamp } from '../admin.v2.format'
import { PageControls, ReadNotice, MutationNotice } from '../admin.management.presentation'
import { PackagePrice } from '../admin.package-price.v2'

function NewProduct({ change, revision, onClose }: { change: SologCatalogChangeRow; revision: number; onClose: () => void }) {
  const store = useManagement(), reference = useManagementQuery('reference', {})
  const [brand, setBrand] = useState(''), [category, setCategory] = useState(''), [mode, setMode] = useState<'Único' | 'Agrupado' | 'Excluido'>('Único'), [group, setGroup] = useState(''), [error, setError] = useState('')
  return <AdminDialog title="Aprobar producto nuevo" onClose={onClose} closeDisabled={!!store.intent('master')?.pending}>{!reference.data ? <ReadNotice {...reference} /> : <form className="admin-v2-form" onSubmit={e => { e.preventDefault(); const payload: Mutations['catalog_change_action'] = { propuesta_fingerprint: change.propuesta_fingerprint, action: 'approve', marca: brand.trim(), categoria_id: category, ...(mode === 'Agrupado' ? { estado: mode, grupo_conteo_id: group } : { estado: mode, grupo_conteo_id: null }) }; setError(''); void store.mutation('catalog_change_action', payload, revision).then(onClose).catch(e => setError(e.message)) }}>
    <p>{change.producto ?? change.c_interno}. Quedará aprobado para publicación; todavía no modifica el catálogo publicado.</p><label>Marca<input required value={brand} onChange={e => setBrand(e.target.value)} /></label><label>Categoría<select required value={category} onChange={e => setCategory(e.target.value)}><option value="">Seleccionar</option>{reference.data.categories.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Modalidad<select value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option>Único</option><option>Agrupado</option><option>Excluido</option></select></label>{mode === 'Agrupado' && <label>Grupo<select required value={group} onChange={e => setGroup(e.target.value)}><option value="">Seleccionar</option>{reference.data.groups.map(g => <option key={g.id} value={g.id}>{g.nombre} · {g.precio}</option>)}</select></label>}<button className="button" disabled={!!store.intent('master')}>Confirmar aprobación</button>
  </form>}{error && <p role="alert">{error}</p>}<MutationNotice domain="master" onSuccess={onClose} /></AdminDialog>
}
function PriceResolution({ fingerprint, onClose }: { fingerprint: string; onClose: () => void }) {
  const store = useManagement(), query = useManagementQuery('price_mismatch_options', { propuesta_fingerprint: fingerprint }), [error, setError] = useState(''), [pack, setPack] = useState(false)
  return <AdminDialog title="Resolver precio del grupo" onClose={onClose} closeDisabled={!!store.intent('master')?.pending}>
    {!query.data ? <ReadNotice {...query} /> : <><p>Precio propuesto: {query.data.nuevo_precio}. Estado: {query.data.change_state}.</p><ul>{query.data.members.map(m => <li key={m.c_interno}>{m.c_interno} · {m.producto} · {m.precio}</li>)}</ul><p>La resolución prepara la publicación; no publica el catálogo. Si se interrumpe, vuelve a esta propuesta aprobada para continuar.</p>{query.data.options.map(option => <button className="button" key={option} disabled={!!store.intent('master') || query.data!.change_state !== 'aprobado'} onClick={() => { setError(''); void store.mutation('resolve_group_price', { propuesta_fingerprint: fingerprint, resolution: option }, query.data!.revisions.groups).then(onClose).catch(e => setError(e.message)) }}>{option === 'update_group_price' ? 'Actualizar precio de todo el grupo' : 'Separar SKU como Único'}</button>)}{query.data.unidades_por_paquete !== null && query.data.unidades_por_paquete > 1 && <button className="button button--secondary" onClick={() => setPack(true)}>Actualizar precio x{query.data.unidades_por_paquete}</button>}<p>El precio por paquete es independiente y solo se actualiza con aceptación explícita.</p></>}
    {error && <p role="alert">{error}</p>}<MutationNotice domain="master" onSuccess={onClose} />{pack && query.data && <PackagePrice groupId={query.data.grupo_id} onClose={() => setPack(false)} />}
  </AdminDialog>
}
function ChangeDetail({ change, revision, onClose }: { change: SologCatalogChangeRow; revision: number; onClose: () => void }) {
  const store = useManagement(), [error, setError] = useState(''), [newProduct, setNewProduct] = useState(false), [resolve, setResolve] = useState(false)
  const act = (action: 'approve' | 'ignore' | 'withdraw') => {
    if (action === 'approve' && change.tipo === 'agregar_producto') { setNewProduct(true); return }
    setError(''); void store.mutation('catalog_change_action', { propuesta_fingerprint: change.propuesta_fingerprint, action }, revision).then(() => {
      if (action === 'approve' && change.tipo === 'precio' && change.catalogo_actual.estado === 'Agrupado') setResolve(true)
      else onClose()
    }).catch(e => setError(e.message))
  }
  if (resolve) return <PriceResolution fingerprint={change.propuesta_fingerprint} onClose={onClose} />
  if (newProduct) return <NewProduct change={change} revision={revision} onClose={onClose} />
  return <AdminDialog title={change.producto ?? `Propuesta ${change.c_interno ?? change.grupo_id}`} onClose={onClose} closeDisabled={!!store.intent('master')?.pending} wide><p>{change.tipo} · {change.estado} · {change.ambito}</p><p>{change.occurrence_count} apariciones · {change.sedes.map(s => s.nombre).join(', ')}</p><h3>Catálogo actual</h3><dl className="admin-v2-data">{Object.entries(change.catalogo_actual).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v ?? '—'}</dd></div>)}</dl><h3>Propuesta autoritativa</h3><pre className="admin-v2-json">{JSON.stringify(change.datos, null, 2)}</pre><div className="admin-v2-actions">{change.estado === 'pendiente' && <><button className="button" disabled={!!store.intent('master')} onClick={() => act('approve')}>Aprobar</button><button className="button button--secondary" disabled={!!store.intent('master')} onClick={() => act('ignore')}>Ignorar propuesta</button></>}{change.estado === 'aprobado' && <><button className="button button--secondary" disabled={!!store.intent('master')} onClick={() => act('withdraw')}>Retirar aprobación</button>{change.tipo === 'precio' && change.catalogo_actual.estado === 'Agrupado' && <button className="button" onClick={() => setResolve(true)}>Resolver precio del grupo</button>}</>}</div>{error && <p role="alert">{error}</p>}<MutationNotice domain="master" onSuccess={payload => { if (payload.action === 'approve' && change.tipo === 'precio' && change.catalogo_actual.estado === 'Agrupado') setResolve(true); else onClose() }} /></AdminDialog>
}
function Publication({ onClose }: { onClose: () => void }) {
  const store = useManagement(), query = useManagementQuery('publication_preview', {}), admin = useAdminStore().bootstrap?.identity.rol === 'admin'
  const p = query.data?.preview, receipt = store.publication
  return <AdminDialog title="Publicar catálogo" onClose={onClose} closeDisabled={!!receipt.pending} wide>
    {p ? <><p>{p.codigo}</p>{p.ok && <><p>Versión {p.version_actual} → {p.version_nueva} · {p.cambios_total} cambios</p><dl className="admin-v2-data">{Object.entries(p.cambios).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></>}{p.errores?.map((e, i) => <p role="alert" key={i}>{e}</p>)}{p.conflictos?.map((c, i) => <p role="alert" key={i}>{c.codigo}: {c.mensaje}</p>)}</> : <ReadNotice {...query} />}
    {receipt.operationId && <p>Publicación pendiente de confirmar: {receipt.operationId}. Reintentar conserva la misma reserva.</p>}{receipt.error && <p role="alert">{receipt.error}</p>}{receipt.result && <p role="status">{receipt.result.codigo} · versión {receipt.result.version}{receipt.result.replay ? ' · replay confirmado' : ''}</p>}
    <button className="button" disabled={!admin || !!receipt.pending || (!receipt.operationId && !p?.puede_publicar)} onClick={() => void store.publish().catch(() => {})}>{receipt.pending ? 'Publicando…' : receipt.operationId ? 'Reintentar publicación' : 'Confirmar publicación'}</button>{!admin && <p>Solo admin puede publicar.</p>}
  </AdminDialog>
}
export function AdminCatalogV2() {
  const [filters, setFilters] = useState<ReadPayloads['catalog_changes']>({ limit: 50, offset: 0 }), [search, setSearch] = useState(''), [code, setCode] = useState(''), [selected, setSelected] = useState<{ change: SologCatalogChangeRow; revision: number } | null>(null), [publishing, setPublishing] = useState(false)
  const query = useManagementQuery('catalog_changes', filters), status = useManagementQuery('status', {}), store = useManagement()
  return <><section className="admin-v2-card"><div className="admin-v2-toolbar"><div><h2>Catálogo compartido</h2>{status.data ? <p>Versión {status.data.catalog.version_actual ?? 'sin publicar'} · {adminTimestamp(status.data.catalog.publicado_at)}</p> : <ReadNotice {...status} />}</div><button className="button" onClick={() => setPublishing(true)}>{store.publication.operationId ? 'Recuperar publicación' : 'Revisar publicación'}</button></div></section><MutationNotice domain="master" />
    <form className="admin-v2-filters" onSubmit={e => { e.preventDefault(); setFilters({ ...filters, producto: search || undefined, c_interno: code ? Number(code) : undefined, offset: 0 }) }}><label>Producto<input value={search} onChange={e => setSearch(e.target.value)} /></label><label>C. interno<input type="number" min="0" value={code} onChange={e => setCode(e.target.value)} /></label><label>Estado<select value={filters.estado ?? ''} onChange={e => setFilters({ ...filters, estado: e.target.value as SologCatalogChangeRow['estado'] || undefined, offset: 0 })}><option value="">Todos</option>{['pendiente', 'aprobado', 'ignorado', 'incorporado'].map(v => <option key={v}>{v}</option>)}</select></label><label>Tipo<select value={filters.tipo ?? ''} onChange={e => setFilters({ ...filters, tipo: e.target.value as SologCatalogChangeRow['tipo'] || undefined, offset: 0 })}><option value="">Todos</option>{['agregar_producto', 'eliminar_producto', 'nombre', 'precio', 'codigo', 'clasificacion_producto', 'definicion_grupo'].map(v => <option key={v}>{v}</option>)}</select></label><label>Ámbito<select value={filters.ambito ?? ''} onChange={e => setFilters({ ...filters, ambito: e.target.value as 'producto' | 'grupo' || undefined, offset: 0 })}><option value="">Todos</option><option>producto</option><option>grupo</option></select></label><button className="button">Filtrar</button></form>
    {query.data ? <><div className="admin-v2-kpis">{Object.entries(query.data.counts).map(([k, v]) => <span key={k}>{k}: <strong>{v}</strong></span>)}</div><div className="admin-v2-table"><table><thead><tr><th>Producto / grupo</th><th>Tipo</th><th>Prioridad</th><th>Estado</th><th>Repeticiones</th><th>Detalle</th></tr></thead><tbody>{query.data.rows.map(c => <tr key={c.propuesta_fingerprint}><td>{c.producto ?? c.grupo_id ?? c.c_interno}</td><td>{c.tipo}</td><td>{c.seccion}</td><td>{c.estado}</td><td>{c.occurrence_count}</td><td><button className="button button--secondary" onClick={() => setSelected({ change: c, revision: query.data!.revisions.groups })}>Ver propuesta</button></td></tr>)}</tbody></table></div><PageControls offset={filters.offset} length={query.data.rows.length} onChange={offset => setFilters({ ...filters, offset })} /></> : <ReadNotice {...query} />}
    {selected && <ChangeDetail change={selected.change} revision={selected.revision} onClose={() => setSelected(null)} />}{publishing && <Publication onClose={() => setPublishing(false)} />}
  </>
}
